### ISSUE TITLE
Tried the script but always fails

### ISSUE THREAD

**Issue by gobigdave** [stevezau/plex_generate_vid_previews#14]
When I run the script, it failed with hundreds of:

ERROR    | __main__:process_item:204 - Failed to load library from
libmediainfo.so.0 - libmediainfo.so.0: cannot open shared object file: No such file or directory

MediaInfo and all other dependencies are installed. 

My plex server is in docker on the same machine as the script. I’m running with the Ubuntu server.

FYI, I tried your script because my video thumbnails do not seem to be generating normally anymore. Other than that, however, my server is working fine.

**Comment by stevezau** [comment]
Hi, The script uses the mediainfo python module. seems it cannot find the lib for some reason..

are you running the script in the docker container? 

Can you run mediainfo standalone? 

What happens if you run "python3 -c "from pymediainfo import MediaInfo""

**Comment by stevezau** [comment]
Closing as I never heard from back you.

**Comment by mlo-Tek** [comment]
Hi,

even if this is already closed, it seems that i am too stupid to run this script. So i have created a docker container manually on my unraid system which basically looks like this:

<img width="1307" alt="Image" src="https://github.com/user-attachments/assets/3edd6ff9-bd84-4563-93b7-cfb26d3aa966" />

When i try to start the container, it instantly fails with the following error in the logs:

```
Traceback (most recent call last):
  File "/app/plex_generate_previews.py", line 117, in <module>
    plex = PlexServer(PLEX_URL, PLEX_TOKEN, timeout=PLEX_TIMEOUT, session=session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/plexapi/server.py", line 116, in __init__
    data = self.query(self.key, timeout=self._timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/plexapi/server.py", line 759, in query
    response = method(url, headers=headers, timeout=timeout, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=32400): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x14a2d0d88e00>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

Unraid also did not create any "plex_gpu_preview" folder in the `/appdata` directory as it normally does while installing an docker image.

I am totally lost. I even tried to follow your "Unraid guide" but failed completely 👎

**Comment by stevezau** [comment]
Hey @hAMMERlized you need to set the plex url to the IP where plex is running. You have set it to localhost.

**Comment by mlo-Tek** [comment]
Damn, thanks for the quick response. Yea i thought so too, but where can i edit the IP? Like i've said, there is no folder within the `appdata` folder. No script file etc.?!

Sorry for being such an butthole..

**Comment by stevezau** [comment]
hmm, you need to set the env variables and map your folders as per the readme? Do you know how to do that? if you haven't used docker before this might be a bit of a stretch

**Comment by mlo-Tek** [comment]
Well as i understood your "Unraid Guide" there is no need of using a docker template at all? Just editing the .py file in the ENV part and save the .py file within a directory? In my case i saved it in /mnt/cache/appdata/plex/Library/Application Support/Plex Media Server/scripts

After running the script manually (within the .../scripts folder) i had to install a bunch of python 3 files and finally i've got the info to install ffmpeg. And this is where i have been stucked.

So, not sure what's the right way to get it done tbh.

**Comment by mlo-Tek** [comment]
Ok, seems as i have got it working. Following your "Unraid Guide". But, for some reason it skips all my files.

```
2025/06/19 00:55:58 | ⚠️  - Skipping as file not found /data/media/tv_kids/Timmy Time/Season 3/Timmy Time - Timmy on Safari - 
S03E17.mkv
2025/06/19 00:55:58 | ⚠️  - Skipping as file not found /data/media/tv_kids/Timmy Time/Season 3/Timmy Time - Timmy Shapes Up - 
S03E18.mkv
2025/06/19 00:55:58 | ⚠️  - Skipping as file not found /data/media/tv_kids/Timmy Time/Season 3/Timmy Time - Timmy and the Dragon -
S03E19.mkv
2025/06/19 00:55:58 | ⚠️  - Skipping as file not found /data/media/tv_kids/Timmy Time/Season 3/Timmy Time - Timmy's Bouncy Friend -
S03E20.mkv
2025/06/19 00:55:58 | ⚠️  - Skipping as file not found /data/media/tv_kids/Timmy Time/Season 3/Timmy Time - Timmy's Twin - 
S03E21.mkv
2025/06/19 00:55:58 | ⚠️  - Skipping as file not found /data/media/tv_kids/Timmy Time/Season 3/Timmy Time - Timmy the Hero - 
S03E22.mkv
2025/06/19 00:55:58 | ⚠️  - Skipping as file not found /data/media/tv_kids/Timmy Time/Season 3/Timmy Time - Fix It Timmy - 
S03E23.mkv
2025/06/19 00:55:58 | ⚠️  - Skipping as file not found /data/media/tv_kids/Timmy Time/Season 3/Timmy Time - Timmy and the Kite - 
S03E24.mkv
2025/06/19 00:55:58 | ⚠️  - Skipping as file not found /data/media/tv_kids/Timmy Time/Season 3/Timmy Time - Timmy's Castle - 
S03E25.mkv
2025/06/19 00:55:58 | ⚠️  - Skipping as file not found /data/media/tv_kids/Timmy Time/Season 3/Timmy Time - Timmy's Scrapbook - 
S03E26.mkv
  Working... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00 701/701
```


This is how my ENV party looks like:


```
PLEX_URL = os.environ.get('PLEX_URL', 'http://10.0.200.13:32400')  # Plex server URL. can also use for local server: http://localhost:32400
PLEX_TOKEN = os.environ.get('PLEX_TOKEN', 'XXX')  # Plex Authentication Token
PLEX_BIF_FRAME_INTERVAL = int(os.environ.get('PLEX_BIF_FRAME_INTERVAL', 10))  # Interval between preview images
THUMBNAIL_QUALITY = int(os.environ.get('THUMBNAIL_QUALITY', 6))  # Preview image quality (2-6)
PLEX_LOCAL_MEDIA_PATH = os.environ.get('PLEX_LOCAL_MEDIA_PATH', '/mnt/cache/appdata/plex/Library/Application Support/Plex Media Server/Media')  # Local Plex media path
TMP_FOLDER = os.environ.get('TMP_FOLDER', '/tmp/plex_gpu_previews')  # Temporary folder for preview generation

PLEX_TIMEOUT = int(os.environ.get('PLEX_TIMEOUT', 60))  # Timeout for Plex API requests (seconds)
PLEX_LIBRARIES = [library.strip().lower() for library in os.environ.get('PLEX_LIBRARIES', '').split(',') if library.strip()]  # Comma-separated list of library names to process, case-insensitive

REGENERATE_THUMBNAILS = os.environ.get('REGENERATE_THUMBNAILS', 'true').strip().lower() in ('true', '1', 'yes')  # Force regeneration of thumbnails

# Path mappings for remote preview generation. # So you can have another computer generate previews for your Plex server
# If you are running on your plex server, you can set both variables to ''
PLEX_LOCAL_VIDEOS_PATH_MAPPING = os.environ.get('PLEX_LOCAL_VIDEOS_PATH_MAPPING', '')  # Local video path for the script
PLEX_VIDEOS_PATH_MAPPING = os.environ.get('PLEX_VIDEOS_PATH_MAPPING', '')  # Plex server video path

GPU_THREADS = int(os.environ.get('GPU_THREADS', 4))  # Number of GPU threads for preview generation
CPU_THREADS = int(os.environ.get('CPU_THREADS', 4))  # Number of CPU threads for preview generation
```

**Comment by stevezau** [comment]
@hAMMERlized you shouldn't share your plex token publicly, i'd recommend you delete that in your above post. 

In regards to the env vars, normally you set them in the docker container setup, not in a env file as you have posted above. I am not familiar with unraid so I cannot help you there, google or chatgpt should tell you how. 

In regards to your errors, that's saying the script/docker container does not have access to /data/media/. Did you map your volumes from your storage into the docker container?
