### ISSUE TITLE
Running on Windows

### ISSUE THREAD

**Issue by samstudent** [stevezau/plex_generate_vid_previews#15]
I know this script was most likely designed to function in a linux environment and I know asking for windows support would be a long shot so I'm reviewing the code to try to see if I can get it running on a Windows box. I've made some changes to manually specify the location of FFMPEG and MediaInfo and I can see it start the FFMPEG process before erroring out with " ERROR    | __mp_main__:process_item:204 - NVML Shared Library Not Found" . If you can think of anything that might get it going forward let me know, I'll keep trying to move it forward.

**Comment by stevezau** [comment]
I believe that is something to do with the NVIDIA lib... I am not sure where to start debugging on windows tho.

**Comment by samstudent** [comment]
I was able to get it working by following the steps you linked and manually moving the dll. Thank you very much!
