### ISSUE TITLE
Generate previews only for newly added media

### ISSUE THREAD

**Issue by sarthakps** [stevezau/plex_generate_vid_previews#18]
Hi! Thanks for the script. It's amazing. I used the script to generate previews for my library a while back. It however took quite a while owing to my library's size. Since then, I've added some new media to my library. If I run the script again, is it going to regenerate previews for the movies/shows for which I'd already generated the previews before? Or is it only going to process the new movies?

**Comment by stevezau** [comment]
the script only processes items if the thumbnails don't exist already. So yes, you should be able to run it again.
