### ISSUE TITLE
Question on How to set the paths in the script

### ISSUE THREAD

**Issue by bartolomesoriano** [stevezau/plex_generate_vid_previews#20]
How should I set the following paths:

PLEX_LOCAL_VIDEOS_PATH_MAPPING = '/path/this/script/sees/to/video/library'
PLEX_VIDEOS_PATH_MAPPING = '/path/plex/sees/to/video/library'

Both my libraries (Movies, TV Shows), consist of multiple folders, so I am not sure about how to set these paths in order to run the script.  I am running the script on Windows (my Plex server is on the same Windows 11 machine), and all my media is on Synology NAS, connected via SMB.

**Comment by stevezau** [comment]
Hi,

I have updated the script to better describe what those path mappings do. 

If you are running on the same machine you should be able to set both variables to blank, so ''. As those variables are used to path paths if the script is running on another machine.

**Comment by bartolomesoriano** [comment]
Thanks!
