### ISSUE TITLE
Fails to create previews of DV-only content

### ISSUE THREAD

**Issue by booleangit** [stevezau/plex_generate_vid_previews#23]
When a movie only contains DV profile 5, the creation of previews fails.

![image](https://github.com/stevezau/plex_generate_vid_previews/assets/25500731/cd19687c-5006-4150-872f-f878981a8d48)

**Comment by stevezau** [comment]
The script is mostly a wrapper for FFmpeg etc so I'm not 100% sure what could be causing that. 

Does this happen for all DV content as i didn't see it happen for me?

**Comment by stevezau** [comment]
@booleangit following up on ^?

**Comment by stevezau** [comment]
Closing due to no reply.
