### ISSUE TITLE
'NoneType' object is not iterable, for all un-processed media

### ISSUE THREAD

**Issue by ABriancourt** [stevezau/plex_generate_vid_previews#24]
Hi. Nice work on this script.

I'm running this on Windows Server 2019 and seeing " 'NoneType' object is not iterable" at line 214 appear for every bit of media that the built-in Plex Thumbnail Generator hasn't yet procesed. Annoyingly this isn't the line where the error seems to be occurring, just where the script is at when it prints that line to stdout, so knowing where the fault actually lies is a bit elusive. I've had a look at the code, but it isnt immediately obvious what the 'NoneType' object is referring to, because the script is correctly pulling the number of episodes (27k+) from Plex.

'NoneType' would normaly mean that something further up the chain is returning a 'None' object and passing is down the chain whereby your script is expecting a list or dict of some kind, and isn't yet handling this potential failure mode or anticipating receiving a None object.

Any ideas what is delivering a 'None' object to your 'process_item' function?

**Comment by stevezau** [comment]
can you paste the stack trace or logs?

**Comment by ABriancourt** [comment]
Good news, I found the culprit.

Line 111:
gpu_ffmpeg = [c for c in gpu.processes if c["command"].lower() == 'ffmpeg']
is the thing returning 'None'. Encapsulating it in the following try/except clause fixed the problem and allows the script to successfully continue:

try:
    gpu_ffmpeg = [c for c in gpu.processes if c["command"].lower() == 'ffmpeg']
except:
    gpu_ffmpeg = []

(excuse for formatting, I don't usually github)

I'm not sure if this is related to the fact that I'm running a Quadro P2000 card and so have unlimited NVENC/ HW Decode sessions and that line is what you script is querying using gpustat, which is returning none because there are no limitations?

Anyway, the above fixed it for me. If it helps you or others in future, enjoy!

**Comment by stevezau** [comment]
Hey @ABriancourt, hmm i have a p5000 so i am not sure "unlimited" is the issue here. 

I added more logging. Are you able to run it again for me and print the stack trace?

**Comment by ABriancourt** [comment]
Curious! Happy to oblige however, see below:

Traceback (most recent call last):

  File "<string>", line 1, in <module>
  File "C:\Program Files\Python312\Lib\multiprocessing\spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               │     │   └ 304
               │     └ 3
               └ <function _main at 0x000002B69B510E00>
  File "C:\Program Files\Python312\Lib\multiprocessing\spawn.py", line 135, in _main
    return self._bootstrap(parent_sentinel)
           │    │          └ 304
           │    └ <function BaseProcess._bootstrap at 0x000002B69B2FB2E0>
           └ <SpawnProcess name='SpawnProcess-2' parent=23804 started>
  File "C:\Program Files\Python312\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
    │    └ <function BaseProcess.run at 0x000002B69B2FA840>
    └ <SpawnProcess name='SpawnProcess-2' parent=23804 started>
  File "C:\Program Files\Python312\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <SpawnProcess name='SpawnProcess-2' parent=23804 started>
    │    │        │    └ (<concurrent.futures.process._SafeQueue object at 0x000002B69EA48EF0>, <multiprocessing.queues.SimpleQueue object at 0x000002...
    │    │        └ <SpawnProcess name='SpawnProcess-2' parent=23804 started>
    │    └ <function _process_worker at 0x000002B69B879800>
    └ <SpawnProcess name='SpawnProcess-2' parent=23804 started>
  File "C:\Program Files\Python312\Lib\concurrent\futures\process.py", line 258, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
        │         │   │         │       │         └ {}
        │         │   │         │       └ <concurrent.futures.process._CallItem object at 0x000002B69B827E00>
        │         │   │         └ ('/library/metadata/2708', <AcquirerProxy object, typeid 'Lock' at 0x2b69efc6ff0>)
        │         │   └ <concurrent.futures.process._CallItem object at 0x000002B69B827E00>
        │         └ <function process_item at 0x000002B69EAA6AC0>
        └ <concurrent.futures.process._CallItem object at 0x000002B69B827E00>

  File "C:\PlexVPTGenerator\go2.py", line 213, in process_item
    generate_images(media_part.attrib['file'], tmp_path, lock)
    │               │          │               │         └ <AcquirerProxy object, typeid 'Lock' at 0x2b69efc6ff0>
    │               │          │               └ 'C:/PlexVPTGenerator/WorkingFolder\\949dbbedd1c7cdd3caceaa531f847e7a23647c86'
    │               │          └ <attribute 'attrib' of 'xml.etree.ElementTree.Element' objects>
    │               └ <Element 'MediaPart' at 0x000002B69EFD4450>
    └ <function generate_images at 0x000002B69E83BE20>

> File "C:\PlexVPTGenerator\go2.py", line 112, in generate_images
    gpu_ffmpeg = [c for c in gpu.processes if c["command"].lower() == 'ffmpeg']
                             │   └ <property object at 0x000002B69DC5C900>
                             └ [0] Quadro P2000     | 33°C,  12 % |   632 /  5120...

TypeError: 'NoneType' object is not iterable
⠼ Working... ━━━━                                      11% 0:05:16  3075/278392023-10-16 02:16:34.333 | ERROR    | __mp_main__:generate_images:114 - Problem getting GPU stats
⠴ Working... ━━━━                                      11% 0:05:16  3075/278392023-10-16 02:16:34.335 | ERROR    | __mp_main__:generate_images:115 - 'NoneType' object is not iterable

**Comment by stevezau** [comment]
hmm. can you edit the code with the below and try again.. just trying to see exactly where it is failing

```
    with lock:
        try:
            gpu_stats_query = gpustat.core.new_query()
            gpu = gpu_stats_query[0]
            gpu_ffmpeg = [c for c in gpu.processes if c["command"].lower() == 'ffmpeg']
        except Exception as error:
            logger.exception(error)
            logger.error(gpu_stats_query)
            logger.error(gpu.processes)
            logger.error(gpu)
            logger.error('Problem getting GPU stats')
            gpu_ffmpeg = []
        if len(gpu_ffmpeg) < GPU_THREADS or CPU_THREADS == 0:
            hw = True
            args.insert(5, "-hwaccel")
            args.insert(6, "cuda")


```

**Comment by ABriancourt** [comment]
Traceback (most recent call last):

  File "<string>", line 1, in <module>
  File "C:\Program Files\Python312\Lib\multiprocessing\spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               │     │   └ 160
               │     └ 3
               └ <function _main at 0x000001E8BD990E00>
  File "C:\Program Files\Python312\Lib\multiprocessing\spawn.py", line 135, in _main
    return self._bootstrap(parent_sentinel)
           │    │          └ 160
           │    └ <function BaseProcess._bootstrap at 0x000001E8BD77B2E0>
           └ <SpawnProcess name='SpawnProcess-6' parent=16068 started>
  File "C:\Program Files\Python312\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
    │    └ <function BaseProcess.run at 0x000001E8BD77A840>
    └ <SpawnProcess name='SpawnProcess-6' parent=16068 started>
  File "C:\Program Files\Python312\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <SpawnProcess name='SpawnProcess-6' parent=16068 started>
    │    │        │    └ (<concurrent.futures.process._SafeQueue object at 0x000001E8C0E9CE30>, <multiprocessing.queues.SimpleQueue object at 0x000001...
    │    │        └ <SpawnProcess name='SpawnProcess-6' parent=16068 started>
    │    └ <function _process_worker at 0x000001E8BDCF9800>
    └ <SpawnProcess name='SpawnProcess-6' parent=16068 started>
  File "C:\Program Files\Python312\Lib\concurrent\futures\process.py", line 258, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
        │         │   │         │       │         └ {}
        │         │   │         │       └ <concurrent.futures.process._CallItem object at 0x000001E8C146EE10>
        │         │   │         └ ('/library/metadata/2844', <AcquirerProxy object, typeid 'Lock' at 0x1e8c0fb82c0>)
        │         │   └ <concurrent.futures.process._CallItem object at 0x000001E8C146EE10>
        │         └ <function process_item at 0x000001E8C0EF6AC0>
        └ <concurrent.futures.process._CallItem object at 0x000001E8C146EE10>

  File "C:\PlexVPTGenerator\go2.py", line 219, in process_item
    generate_images(media_part.attrib['file'], tmp_path, lock)
    │               │          │               │         └ <AcquirerProxy object, typeid 'Lock' at 0x1e8c0fb82c0>
    │               │          │               └ 'C:/PlexVPTGenerator/WorkingFolder\\a200620dd4df9c80a37d8e80b84dd3b79ca1d48c'
    │               │          └ <attribute 'attrib' of 'xml.etree.ElementTree.Element' objects>
    │               └ <Element 'MediaPart' at 0x000001E8C147BF10>
    └ <function generate_images at 0x000001E8C0C7FE20>

> File "C:\PlexVPTGenerator\go2.py", line 113, in generate_images
    gpu_ffmpeg = [c for c in gpu.processes if c["command"].lower() == 'ffmpeg']
                             │   └ <property object at 0x000001E8C005C9A0>
                             └ [0] Quadro P2000     | 32°C,   7 % |   580 /  5120...

TypeError: 'NoneType' object is not iterable
⠼ Working... ━━━━╸                                     12% 0:06:14  3217/278412023-10-16 02:56:30.880 | ERROR    | __mp_main__:generate_images:116 - GPUStatCollection(host=REDACTED, [
  [0] Quadro P2000     | 32°C,   7 % |   580 /  5120 MB | (Not Supported)
])
2023-10-16 02:56:30.908 | ERROR    | __mp_main__:generate_images:117 - None
2023-10-16 02:56:30.910 | ERROR    | __mp_main__:generate_images:118 - [0] Quadro P2000     | 32°C,   7 % |   580 /  5120 MB | (Not Supported)
2023-10-16 02:56:30.932 | ERROR    | __mp_main__:generate_images:119 - Problem getting GPU stats
⠦ Working... ━━━━╸                                     12% 0:06:14  3217/278412023-10-16 02:56:31.974 | ERROR    | __mp_main__:generate_images:115 - 'NoneType' object is not iterable

**Comment by stevezau** [comment]
Ok, i pushed a change that checks if gpustats returns an object. For some reason it is not for you.. Not really a great fix but to fix it properly i'd need to reproduce which i can't.
