### ISSUE TITLE
 ERROR    | __mp_main__:process_item:221 

### ISSUE THREAD

**Issue by tristan7187** [stevezau/plex_generate_vid_previews#28]
Running on windows, i keep getting the same error when its trying to process my movies,  "ERROR    | __mp_main__:process_item:221" it will go threw all my movies with that same error, then stall out when it hits the TV section, i already saw the other issue about running on windows that has been closed, but my problem seems not related to that.

**Comment by stevezau** [comment]
I just updated line 221 to print out a stack trace. Can you try again with the latest script?

Paste the output here.

**Comment by tristan7187** [comment]
I put the output in the error.txt, but it looks like a file not found error..Im running the script remotely so i thought issue might be how i have "PLEX_LOCAL_VIDEOS_PATH_MAPPING" setup but i double checked the formatting in ChatGPT and it seems fine, but i put it in the mypy.txt file just incase.  

[error.txt](https://github.com/stevezau/plex_generate_vid_previews/files/13499930/error.txt)
[mypy.txt](https://github.com/stevezau/plex_generate_vid_previews/files/13499931/mypy.txt)

**Comment by stevezau** [comment]
@tristan7187 i don't think you have configured this correctly. The variables are meant to map from 1 path. You have entered multiple paths in your config? 

also, did you check the file path in the error exists? 
> G:\\Videos\\Movies\\Zombieland.2009.2160p.BluRay.REMUX.HEVC.DTS-HD.MA.TrueHD.7.1.Atmos-FGT.mkv

**Comment by tristan7187** [comment]
My plex library is split across multiple drives, so I thought that was necessary.  But, Yeah the file exists,  I get that same file not found error for every movie in my library, but it definitely finds the find the file cause it will say something like "file not found" then show the exact name and location of the file like "G:\Videos\Movies\Zombieland.2009.2160p.BluRay.REMUX.HEVC.DTS-HD.MA.TrueHD.7.1.Atmos-FGT.mkv" , so it definitely see the file. But its all good, I just been doing it regularly threw plex, appreciate the help tho.

**Comment by stevezau** [comment]
Hey @tristan7187 are you running this script on the plex server and does the data also live on that plex server?

If so, you can leave those mapping lines empty and you should't need them. If not, the script does not support multiple path mappings.

**Comment by stevezau** [comment]
Closing this due to no reply.
