### ISSUE TITLE
Possibility to release as docker container?

### ISSUE THREAD

**Issue by jonboy345** [stevezau/plex_generate_vid_previews#29]
Just curious about your thoughts on building and releasing this as a docker container to simplify deployment and use of the script.

Thank you.

**Comment by stevezau** [comment]
Sure, it would make sense. Are you suggesting you want to give it a go? :)

**Comment by jonboy345** [comment]
I'm not smart enough to make that happen. Just making a feature request. Glad to help test, though. 

:)

**Comment by stevezau** [comment]
I'll leave this open if someone else wants to tackle it.

**Comment by stevezau** [comment]
should be done in a few days. you can monitor here https://github.com/stevezau/plex_generate_vid_previews/pull/32

**Comment by stevezau** [comment]
@jonboy345 it's done. checkout the readme now
