### ISSUE TITLE
[Errno 2] No such file or directory when writing out .bif

### ISSUE THREAD

**Issue by jasonsansone** [stevezau/plex_generate_vid_previews#3]
If the "Indexes" directory does not exist inside Contents, the script throws an error.  In reviewing the code, I see a mkdir for the tmp folder but I didn't see one for the bundle_path.  However I am not a programmer in anyway.

```
[Errno 2] No such file or directory:
'/var/lib/plexmediaserver/Library/Application Support/Plex Media 
Server/Media/localhost/8/06faad73082ea7937e85af3f2ac98f7136baad0.bundle/Contents/Indexes/index-sd.bif'
```

**Comment by jasonsansone** [comment]
I’m an idiot. It’s just a permissions issue. I was running python as a different user than the Plex user. I will need to execute the python script as my Plex user. Possibly a good mention in docs.

**Comment by jasonsansone** [comment]
Permissions is only half the issue.  For anyone that wishes to fix that, or as possible code revisions, do the following.

1.  Add a line below Line 1 and 2 with `import os`
2. After the CPU_THREAD variable, add two new variables.  These need to match the UID and GUID of your Plex process.
`PLEX_UID = 1000
PLEX_GUID = 1001`
3. Before "console..." and after the above new variables add these two lines:
`os.setgid(PLEX_GUID)
os.setuid(PLEX_UID)`


Those code changes allow the python script to run as any user and group you define, even if the shell user is logged in as root.


The second problem is actually my original problem.  The code does not create the full directory path before writing the index-sd.bif file even if it does not exist.  A two line revision to the `def process_item` code block fixes it.  Just add the following after `tmp_path = os.path.join(TMP_FOLDER, bundle_hash)`:
```
                if not os.path.isdir(indexes_path):
                    os.mkdir(indexes_path)
```

**Comment by stevezau** [comment]
Would you be open to creating a PR?

**Comment by stevezau** [comment]
@jasonsansone this fixed given your PR, right? We can close this?

**Comment by jasonsansone** [comment]
Resolved with PR
