### ISSUE TITLE
Issue or user error?

### ISSUE THREAD

**Issue by Paradoxum** [stevezau/plex_generate_vid_previews#34]
![image](https://github.com/stevezau/plex_generate_vid_previews/assets/6451395/334ef264-12c3-4faa-9bea-ded7fe655f18)

docker run -it --rm \
  --name=plex_generate_vid_previews \
  --runtime=nvidia \
  -e NVIDIA_VISIBLE_DEVICES=all \
  -e PUID=1000 \
  -e PGID=1000 \
  -e PLEX_URL='http://192.168.2.1:32400' \
  -e PLEX_TOKEN='wX99567567567xYxXMr' \
  -e PLEX_BIF_FRAME_INTERVAL=2 \
  -e THUMBNAIL_QUALITY=2 \
  -e PLEX_LOCAL_MEDIA_PATH='/Media/localhost/' \
  -e GPU_THREADS=5 \
  -e CPU_THREADS=5 \
  -v /mnt/user/data/media/tv:/your/media/files \
  -v /mnt/user/Plex/:/plex/folder \
  stevezzau/plex_generate_vid_previews:latest

running unraid using hotios plexpass container.

someone on irc says it could be because the script mentions linuxservers container and that uses a different dir structure (which is what you have as default).

![image](https://github.com/stevezau/plex_generate_vid_previews/assets/6451395/02cb1300-6a66-4a0b-88dd-04b102d5e257)
/Plex/ here is the root;
![image](https://github.com/stevezau/plex_generate_vid_previews/assets/6451395/9cde17d8-f9ca-450d-b935-7ae5e9186415)

and then /Media/localhost/ is where your default location would point to. Am I setting it up correctly or?

Thanks in advance.

**Comment by stevezau** [comment]
Hi, i don't think you set the variables correctly.

You said your Plex folder exists in /Plex right? 
But you set `-e PLEX_LOCAL_MEDIA_PATH='/Media/localhost/'`. It prob should be `-e PLEX_LOCAL_MEDIA_PATH='/Plex/Media'`


You also didn't map your plex folder correctly so the container has access.

So the below maps /Plex from the server/host to /Plex in the container.
`-v /Plex:/Plex`

**Comment by Paradoxum** [comment]
Plex root dir exists in /mnt/user/Plex which is a share in unraid, named 
Plex, does it know if I put /Plex I am referring to a share?


------ Original Message ------
From "Steve Adams" ***@***.***>
To "stevezau/plex_generate_vid_previews" 
***@***.***>
Cc "Paradoxum" ***@***.***>; "Author" 
***@***.***>
Date 15/04/2024 3:08:16 AM
Subject Re: [stevezau/plex_generate_vid_previews] Issue or user error? 
(Issue #34)

**Comment by stevezau** [comment]
Can you give me more contact on how you are running this?

Where is docker located, where is plex located. Same server or different?

Where are the plex library files (tvshows and movies etc)

Where are the plex server files located (/mnt/user/Plex) as you suggested.

**Comment by Paradoxum** [comment]
Same server.
![image](https://github.com/stevezau/plex_generate_vid_previews/assets/6451395/a6d2f463-2de2-4785-a41b-4ec587a3b9cb)

These are the mapped folders for the plex container.

Plex file would NORMALLY be in /mnt/user/appdata/plex, but I use an M2 drive for plex so they exist in a share named Plex so /mnt/user/Plex

I am, but I've never done a docker cli before.

**Comment by stevezau** [comment]
You need to map your volumes in the docker container correctly https://docs.docker.com/storage/volumes/

So you need to edit the -v settings so this docker container has access to the same files/paths as your plex docker container. 

make sense?

**Comment by stevezau** [comment]
That's not bash; your comment didn't execute. Sorry, but are you familiar with Linux?

**Comment by Paradoxum** [comment]
sop /your/media/files needs to be what plex has for /mnt/user/data/media/anime/movies also? that is not made clear if so.

**Comment by zaheria985** [comment]
I came here with same questions...

I think when you refer to this: Path to Plex Media folder, you're referring to the appdata folder for Plex

Still not sure I understand the rest as normally, the host is mapped to what's in the container.  But since this is a script, are you saying you will have the same mapping both inside and outside the container?

It is a bit different

**Comment by stevezau** [comment]
@zaheria985 you can run this as a script or also a docker container. If you choose a docker container then the container must have access to the paths requires, inside the docker container. 

Not sure if i'm not being clear?

>I think when you refer to this: Path to Plex Media folder, you're referring to the appdata folder for Plex
Yes, that's right, perhaps the wording needs updating but i thought it was clear with the example?

**Comment by stevezau** [comment]
@zaheria985 @Paradoxum did you figure it out?

**Comment by Paradoxum** [comment]
This is the one I just used:
docker run -it --rm \
  --name=plex_generate_vid_previews \
  --runtime=nvidia \
  -e NVIDIA_VISIBLE_DEVICES=all \
  -e PUID=1000 \
  -e PGID=1000 \
  -e PLEX_URL='http://192.168.2.90:32400' \
  -e PLEX_TOKEN='wX995XLCetzY3wxYxXMr' \
  -e PLEX_BIF_FRAME_INTERVAL=1 \
  -e THUMBNAIL_QUALITY=2 \
  -e PLEX_LOCAL_MEDIA_PATH='/path/to/plex/media' \
  -e GPU_THREADS=5 \
  -e CPU_THREADS=5 \
  -v /mnt/user/data/media/tv:/videos \
  -v /mnt/user/Plex/:/path/to/plex/media \
  stevezzau/plex_generate_vid_previews:latest

actually seemed to make some progress;
![image](https://github.com/stevezau/plex_generate_vid_previews/assets/6451395/ab84b89a-e63f-4f26-91d4-28ffe5fb055c)

do you have to mount every library in plex? I was assuming it only ran on the ones you had in the config so I was going to test it on one first.

**Comment by stevezau** [comment]
Currently, the script goes through every library in Plex. There hasn't been a need to specify which library.. So, yes all media files will need to mapped correctly. 

However, your error message says it cannot access the folder set by ** PLEX_LOCAL_MEDIA_PATH**. You are using the example value of "/path/to/plex/media". This need to be corrected.

I don't know what your  /mnt/user/Plex folder looks like.. So, i am going to assume.. 

You have mapped /mnt/user/Plex/ to the folder /path/to/plex/media inside the container.

So, I think you need to set it to
-e PLEX_LOCAL_MEDIA_PATH='/path/to/plex/Media'

Make sure the Media folder exists in /mnt/user/Plex/.. Inside the Media folder you should see another folder called localhost.. Then inside that a bunch of folders with a single digit or letter.

On my system the Media folder lives in "Library/Application Support/Plex Media Server/Media".. So if yours is the same you'll need to update that variable. 

does that make sense?

**Comment by Paradoxum** [comment]
I decided to use docker-compose to make it a bit easier because I've used that before.

finally, I figured out the right settings;
version: '3'
services:
  previews:
    image: stevezzau/plex_generate_vid_previews:latest
    environment:
      - PLEX_URL=https://192.168.2.90:32400
      - PLEX_TOKEN=sdfsdf
      - PLEX_BIF_FRAME_INTERVAL=1
      - THUMBNAIL_QUALITY=2
      - PLEX_LOCAL_MEDIA_PATH=/path/to/plex/media
      - TMP_FOLDER=/tmp/previews
      - PLEX_TIMEOUT=60
      - GPU_THREADS=5  
      - CPU_THREADS=5
    volumes:
      - /mnt/user/Plex/:/path/to/plex/media
      - /mnt/user/data/media/tv/:/videos
      - /mnt/user/data/media/movies/:/videos2
      - /mnt/user/data/media/anime/movies/:/videos3
      - /mnt/user/data/media/anime/series/:/videos4
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia

This is the log, it crashes shortly after starting; https://pastebin.com/raw/fY2VpaE5

Thanks

**Comment by stevezau** [comment]
@Paradoxum that's odd. The script checks if that path exists before creating here https://github.com/stevezau/plex_generate_vid_previews/blob/main/plex_generate_previews.py#L225

A couple of questions
1. what filesystem is /mnt/user/Plex/Media ?
2. have you also mapped /mnt/movies inside the container? looking at your docker compose it does not look like you have. The script needs access to the media files 
3. Can you check if /mnt/user/Plex/Media/localhost/b/446eb2552b010cecc4d70b2885bbf7dd2b7f100.bundle/Contents/Indexes does actually exist and is it a file or a folder? What permissions are set?

Thanks

**Comment by Paradoxum** [comment]
BTFRS

This my compose file now:
version: '3'
services:
  previews:
    image: stevezzau/plex_generate_vid_previews:latest
    environment:
      - PLEX_URL=https://192.168.2.90:32400
      - PLEX_TOKEN=claim-zmj74FKvEH62YTv5DSMW
      - PLEX_BIF_FRAME_INTERVAL=1
      - THUMBNAIL_QUALITY=2
      - PLEX_LOCAL_MEDIA_PATH="/mnt/user/Plex/Library/Application Support/Plex Media Server/Media/localhost/"
      - TMP_FOLDER=/tmp/plex_thumb_previews
      - PLEX_TIMEOUT=300
      - GPU_THREADS=40  
      - CPU_THREADS=12
    volumes:
      - "/mnt/user/Plex/Library/Application Support/Plex Media Server/Media/localhost/":"/mnt/user/Plex/Library/Application Support/Plex Media Server/Media/localhost/"
      - /mnt/user/data/media/tv/:/mmt/tv/
      - /mnt/user/data/media/movies/:/mnt/movies
      - /mnt/user/data/media/anime/movies/:/mnt/anime/movies
      - /mnt/user/data/media/anime/series/:/mnt/anime/series
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia


this is what plex looks like:
![image](https://github.com/stevezau/plex_generate_vid_previews/assets/6451395/84ed3540-4229-4075-bffc-e4680fef2e7f)

should this work now? I think my previous attempts corrupted my db or something so I just restarted again anyway since as soon as I can get the tesla generating previews I can do the whole library in a couple weeks probably.

Thanks

**Comment by Paradoxum** [comment]
is this it running?

![image](https://github.com/stevezau/plex_generate_vid_previews/assets/6451395/f2569512-e316-4afc-b5f7-f9f3313f46ba)

**Comment by Paradoxum** [comment]
text  error  warn  system  array  login  

  File "/app/plex_generate_previews.py", line 246, in run
    plex = PlexServer(PLEX_URL, PLEX_TOKEN, session=sess)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/plexapi/server.py", line 116, in __init__
    data = self.query(self.key, timeout=self._timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/plexapi/server.py", line 759, in query
    response = method(url, headers=headers, timeout=timeout, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='192.168.2.90', port=32400): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x14d998953200>: Failed to establish a new connection: [Errno 111] Connection refused'))
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 198, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 616, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 213, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x151a59110470>: Failed to establish a new connection: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='192.168.2.90', port=32400): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x151a59110470>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/plex_generate_previews.py", line 284, in <module>
    run()
  File "/app/plex_generate_previews.py", line 246, in run
    plex = PlexServer(PLEX_URL, PLEX_TOKEN, session=sess)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/plexapi/server.py", line 116, in __init__
    data = self.query(self.key, timeout=self._timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/plexapi/server.py", line 759, in query
    response = method(url, headers=headers, timeout=timeout, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='192.168.2.90', port=32400): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x151a59110470>: Failed to establish a new connection: [Errno 111] Connection refused'))

** Press ANY KEY to close this window **

**Comment by Paradoxum** [comment]
It seemed to stay running one time, but nothing seemed to be happening and that was in the log. I restarted it/plex again a few times and couldn't get it to stay on again. could I get some more instructions on how to use this please?

**Comment by Paradoxum** [comment]
Got a new token and used it in both, started it, this only in log now;

![image](https://github.com/stevezau/plex_generate_vid_previews/assets/6451395/4ed4fb8b-4523-4040-bf08-7ab16447747a)

**Comment by Paradoxum** [comment]
![image](https://github.com/stevezau/plex_generate_vid_previews/assets/6451395/85a78a53-ed0b-4cec-985e-ba20ea5ffe5b)

![image](https://github.com/stevezau/plex_generate_vid_previews/assets/6451395/6cdb4cf2-a516-4fbb-a2a2-e55542ddaeb0)


![image](https://github.com/stevezau/plex_generate_vid_previews/assets/6451395/2529782d-0cf8-4c9f-a519-f58d65168db2)


COMPOSE:
version: '3'
services:
  previews:
    image: stevezzau/plex_generate_vid_previews:latest
    environment:
      - PLEX_URL=http://192.168.2.90:32400
      - PLEX_TOKEN=claim-Kc4utwzuRU7yqpNWEm1y
      - PLEX_BIF_FRAME_INTERVAL=1
      - THUMBNAIL_QUALITY=2
      - PLEX_LOCAL_MEDIA_PATH=/mnt/thumbs/
      - TMP_FOLDER=/tmp/plex_thumb_previews
      - PLEX_TIMEOUT=300
      - GPU_THREADS=40  
      - CPU_THREADS=12
    volumes:
      - /mnt/user/Plex/Library/Application Support/Plex Media Server/Media/localhost/:/mnt/thumbs/
      - /mnt/user/data/media/tv/:/mmt/tv/
      - /mnt/user/data/media/movies/:/mnt/movies/
      - /mnt/user/data/media/anime/movies/:/mnt/anime/movies/
      - /mnt/user/data/media/anime/series/:/mnt/anime/series/
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia
    
    
Some kind of auth error it seems. i tried setting allow insecure connections etc< made everything R/W to all before running.

**Comment by stevezau** [comment]
@Paradoxum , I don't mean to sound harsh, but it looks like the issues you're experiencing are primarily due to user errors. I haven't detected any bugs in the script itself. I’m here to help, but it seems that these are configuration mistakes on your part. Could you recheck your settings? For example, the last message you sent reported a 401 error, which usually indicates that the PLEX_TOKEN you've set is invalid. Could you confirm that it’s correctly configured?

Additionally, your earlier question, "is this it running?" along with the screenshot you posted, suggests a misunderstanding of how Docker operates. That image showed Docker downloading the images, not running them.

**Comment by Paradoxum** [comment]
The last post is the only relevant one now. And yes, I said in a 
previous post the token is correct.


------ Original Message ------
From "Steve Adams" ***@***.***>
To "stevezau/plex_generate_vid_previews" 
***@***.***>
Cc "Paradoxum" ***@***.***>; "Mention" 
***@***.***>
Date 07/05/2024 1:36:07 AM
Subject Re: [stevezau/plex_generate_vid_previews] Issue or user error? 
(Issue #34)

**Comment by stevezau** [comment]
@Paradoxum, the token is either not correct or not set correctly. The error you are receiving is from Plex...

You also posted your token in clear text in this ticket. Please don't do that, it's not a safe practice. 

Lastly, the token you posted is prefixed with "claim-".. Plex tokens, from my experience, are not prefixed with claim- so i am unsure where you got that from. did you follow https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/ correctly?

**Comment by Paradoxum** [comment]
I was using my claim token instead of the api key. working now.

**Comment by Paradoxum** [comment]
It was doing a library fine, but I wanted to start at tv shows and change to another plex container, now I am getting this again
![image](https://github.com/stevezau/plex_generate_vid_previews/assets/6451395/75ab0fcb-f1d1-411b-b151-5219685bd554)

**Comment by stevezau** [comment]
@Paradoxum i am unsure what you are asking me? Looking at your screenshot i am not sure if this script is actually working as it should be outputting the speed but it seems to be outputting errors i think. Is it actually working ? you can see thumbnails generated in plex?

**Comment by Paradoxum** [comment]
Hey,
Would you be able to ship my order next day and I could paypal you the 
difference in a couple days?

Thanks,
Simon


------ Original Message ------
From "Steve Adams" ***@***.***>
To "stevezau/plex_generate_vid_previews" 
***@***.***>
Cc "Paradoxum" ***@***.***>; "Mention" 
***@***.***>
Date 07/05/2024 3:54:33 AM
Subject Re: [stevezau/plex_generate_vid_previews] Issue or user error? 
(Issue #34)

**Comment by stevezau** [comment]
huh?

**Comment by Paradoxum** [comment]
Replied to the thread in email client instead of responding to someone.

**Comment by Paradoxum** [comment]
I seem to have it running now;
![image](https://github.com/stevezau/plex_generate_vid_previews/assets/6451395/84eeed35-5710-489f-af59-d0906d6e0d4f)

However after I did that library I rebooted the server and ran it again - it can't detect they already have thumbs or something?

**Comment by stevezau** [comment]
If I understand what you're asking.. for each item in the library.. it will only generate thumbnails if they don't exist

**Comment by Paradoxum** [comment]
it stayed on that image and showed nothing, I was expecting it to move 
on to the next location (which it did the first time after finishing). 
so now just remove the mount point I guess.


------ Original Message ------
From "Steve Adams" ***@***.***>
To "stevezau/plex_generate_vid_previews" 
***@***.***>
Cc "Paradoxum" ***@***.***>; "Mention" 
***@***.***>
Date 07/05/2024 12:20:29 PM
Subject Re: [stevezau/plex_generate_vid_previews] Issue or user error? 
(Issue #34)

**Comment by stevezau** [comment]
it is prob processing the files.
