### ISSUE TITLE
Too many GPU threads causes unraid lockup

### ISSUE THREAD

**Issue by Paradoxum** [stevezau/plex_generate_vid_previews#35]
I did not know how many theads to put to max out a tesla p4, I found various numbers and started with the highest, 3,000 something. shortly after it starts trying to transcode, unraid locks up completely. I lowered it to 1k, same, now it's at 16 and seems to run fine, but maybe putting 0 could have it use as much as possible if you don't know how many threads to put as the max?

using an i7-10700k and the p4, how many threads should I use from the cpu, all 16? will it cause everything else to slow to a crawl or will it share the cpu fairly? what kind of speed gains do you get from eg 2 threads vs 16 threads?

**Comment by stevezau** [comment]
Hi, @Paradoxum, I am not familiar with that GPU and the max threads it can support. I'd prob say maybe 4-5 threads. But, I'd suggest you do some googling to figure out what is the right amount of threads..

**Comment by ali-ramadhan** [comment]
I know this is an old thread but in case anyone stumbles upon here in the future.

> I did not know how many theads to put to max out a tesla p4, I found various numbers and started with the highest, 3,000 something.

@Paradoxum I'm wondering if you're referring to _CUDA cores_ as the Tesla P4 has 2560 CUDA cores. But these aren't cores in the same way that your CPU has multiple cores. They're much smaller and many are needed to perform any task.

And actually the number of CUDA cores is not indicative of encoding performance. Instead it relies on the [NVENC](https://en.wikipedia.org/wiki/Nvidia_NVENC) capabilities of your GPU as encoding and decoding video is done on a separate chip on your GPU.

You can find more info here but the Tesla P4 has 2 NVENC chips:
* https://developer.nvidia.com/video-encode-and-decode-gpu-support-matrix-new
* https://www.elpamsoft.com/?p=Plex-Hardware-Transcoding

`GPU_THREADS` in this script is more like number of ffmpeg processes using the GPU at once. So it could be bottlenecked by storage media read speeds, CPU, GPU, or GPU VRAM. You'd have to experiment and benchmark what works best for your setup. But probably somewhere between 4 and 20 GPU threads depending on the bottle neck?

I think it makes sense that UNRAID locks up if you try to use like 1000 threads as the script will try to spawn 1000 ffmpeg processes all reading and thrashing your storage at once.
