### ISSUE TITLE
Permissions error or settings for shows? 

### ISSUE THREAD

**Issue by Paradoxum** [stevezau/plex_generate_vid_previews#36]
my compose file:

version: '3'
services:
  previews:
    image: stevezzau/plex_generate_vid_previews:latest
    environment:
      - PLEX_URL=http://192.168.2.90:32400
      - PLEX_TOKEN=zMQQrtertertasNx
      - PLEX_BIF_FRAME_INTERVAL=3
      - THUMBNAIL_QUALITY=2
      - PLEX_LOCAL_MEDIA_PATH=/mnt/thumbs/
      - TMP_FOLDER=/tmp/thumbs/
      - PLEX_TIMEOUT=120
      - GPU_THREADS=8
      - CPU_THREADS=6
    volumes:
      - /mnt/user/Plex/Plex Media Server/Media/localhost:/mnt/thumbs
      - /mnt/user/data/media/anime/movies:/mnt/anime/movies
      - /mnt/user/data/media/tv:/mmt/tv
      - /mnt/user/data/media/movies:/mnt/movies
      - /mnt/user/data/media/anime/series:/mnt/anime/series
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia

it actually ran and did anime movies and regular movies fine. but when it got to the shows, I get this:
![image](https://github.com/stevezau/plex_generate_vid_previews/assets/6451395/c8778314-0eff-48e5-92d8-c141d1152656)

![image](https://github.com/stevezau/plex_generate_vid_previews/assets/6451395/fd02e283-587c-46e0-b45f-98f4da1b089b)

my /data/media/ dir is r/w for all, and it was able to do the movies fine, what exactly does the error 'a red x'? mean. doubt it's permissions when it can do movies fine (just added a new one and it generated that fine.) 

This is a fresh plex install/db so I could generate thumbs for it using my tesla p4. (anyone know how many threads max for that I should put to max it out??) 
The plex drive is at about 90gb now from generating for the movies folders.

Thanks in advance.

**Comment by stevezau** [comment]
@Paradoxum I Added some extra logging. Can you try again with the latest version? Make sure you pull down the latest image if you are using the latest tag.

**Comment by Paradoxum** [comment]
2024/05/27 00:18:08 | ❌  - Problem generating bif images for /mnt/tv/Solar 
Opposites (2020) /Season 03/Solar Opposites (2020) - S03E02 - Edamame Duffle Bag
[HDTV-1080p][EAC3 5.1].mkv due to /mnt/tv/Solar Opposites (2020) /Season 
03/Solar Opposites (2020) - S03E02 - Edamame Duffle Bag [HDTV-1080p][EAC3 
5.1].mkv

**Comment by stevezau** [comment]
@Paradoxum, I just released a new version with more logging to determine why yours is failing. Can you rerun with the 1.03 version? (note: give it 10mins for v 1.03 to appear)

**Comment by Paradoxum** [comment]
<img width="547" alt="image" src="https://github.com/stevezau/plex_generate_vid_previews/assets/6451395/e05191af-3f3b-4c81-9f71-1f874d25fa0a">

**Comment by stevezau** [comment]
@Paradoxum, something is going wrong when running ffmpeg, but it is not clear what is causing it.

 I've uploaded a new version, 1.04, with debug statements. Can you rerun again.

**Comment by Paradoxum** [comment]
updating now.

question re; existing thumbs. if you change the settings, will it re-do 
anything previously done with other settings? how do I find the optimal 
cores to put for cpu/gpu if I just want to max them out doing it [when 
it's working]?
------ Original Message ------
From "Steve Adams" ***@***.***>
To "stevezau/plex_generate_vid_previews" 
***@***.***>
Cc "Paradoxum" ***@***.***>; "Mention" 
***@***.***>
Date 27/05/2024 02:18:33 AM
Subject Re: [stevezau/plex_generate_vid_previews] Permissions error or 
settings for shows? (Issue #36)

**Comment by stevezau** [comment]
It will only generate thumbs if they don't exist. 

You will need to figure out what is the optional as it depends on your hardware. I'd just run it and monitor the cpu / gpu usage.. If you share your CPU version and GPU, I can give you what I think is a good setting, but it would just be a guess.

**Comment by Paradoxum** [comment]
<img width="604" alt="image" src="https://github.com/stevezau/plex_generate_vid_previews/assets/6451395/7b676393-160d-4e4f-94a2-2659c4ac1571">

**Comment by Paradoxum** [comment]
it looks like it's putting an extra space after the (date) in the title and trying to look there?

**Comment by stevezau** [comment]
@Paradoxum can you share the full log? it is cut off at the top.

**Comment by Paradoxum** [comment]
where is the file located?

**Comment by stevezau** [comment]
There is no file. I meant I need the full docker log output.. the screenshot you shared isn't all the output.

**Comment by Paradoxum** [comment]
yeah I can't because the console window closes after it finishes so I 
can only grab what's on the screen as it scrolls off a half second later


------ Original Message ------
From "Steve Adams" ***@***.***>
To "stevezau/plex_generate_vid_previews" 
***@***.***>
Cc "Paradoxum" ***@***.***>; "Mention" 
***@***.***>
Date 27/05/2024 02:37:13 AM
Subject Re: [stevezau/plex_generate_vid_previews] Permissions error or 
settings for shows? (Issue #36)

**Comment by stevezau** [comment]
I am going to need the full log.. there must be a way to get the output. What system are you using?

**Comment by Paradoxum** [comment]
unraid

(obviously music but just posting this)

I let it scroll and tried to copy as much text as I could;
https://pastebin.com/raw/1xJ984tw


------ Original Message ------
From "Steve Adams" ***@***.***>
To "stevezau/plex_generate_vid_previews" 
***@***.***>
Cc "Paradoxum" ***@***.***>; "Mention" 
***@***.***>
Date 27/05/2024 02:40:43 AM
Subject Re: [stevezau/plex_generate_vid_previews] Permissions error or 
settings for shows? (Issue #36)

**Comment by stevezau** [comment]
@Paradoxum hmm, the script gets the path from plex. 

Please check

1. /mnt/tv/ is mounted in the docker container correctly.
2. Check if /mnt/tv/24 (2001) / has a space at the end of it on the filesystem or not...
3. Go to Plex, go to the same 24 episode. And click the three dots (...) and "get info". Take a screenshot and post it here.

Thanks

**Comment by stevezau** [comment]
how did you go @Paradoxum ?

**Comment by Paradoxum** [comment]
Hi,
was away for the day.

the patth on the filesystem is exactly "\\ORBITALHUB\data\media\tv\24 (2001) [imdb-tt0285331]\Season 01" and so on. 

will get back to you with the other things in a bit. thanks

**Comment by Paradoxum** [comment]
> It will only generate thumbs if they don't exist.
> 
> You will need to figure out what is the optional as it depends on your hardware. I'd just run it and monitor the cpu / gpu usage.. If you share your CPU version and GPU, I can give you what I think is a good setting, but it would just be a guess.

when I put the cores for the GPU too high and run it, it will crash Unraid and need to be hard reset. I think 12 cores is the highest I was able to put without it crashing unraid. but I can't find out the specific number of cores to use with my Tesla P4.

**Comment by Paradoxum** [comment]
![image](https://github.com/stevezau/plex_generate_vid_previews/assets/6451395/b83407fb-c539-4060-88a5-836255c88c0b)

**Comment by Paradoxum** [comment]
anything else I can do to help debug?

**Comment by stevezau** [comment]
i'm away atm, will take a look next week.

**Comment by stevezau** [comment]
@Paradoxum are you able to share your plex database with me so I can t-shoot what's going on here?

**Comment by stevezau** [comment]
@Paradoxum are you on discord? would be better & faster If we can live chat also.

**Comment by stevezau** [comment]
@Paradoxum nudge :)

**Comment by Paradoxum** [comment]
hi yes, sunwind.actual on discord.

**Comment by stevezau** [comment]
@Paradoxum is that your username? What community are you in so I can find you?

**Comment by Paradoxum** [comment]
oh I thought you could just message people if you knew their username?


------ Original Message ------
From "Steve Adams" ***@***.***>
To "stevezau/plex_generate_vid_previews" 
***@***.***>
Cc "Paradoxum" ***@***.***>; "Mention" 
***@***.***>
Date 12/06/2024 05:27:18 AM
Subject Re: [stevezau/plex_generate_vid_previews] Permissions error or 
settings for shows? (Issue #36)

**Comment by stevezau** [comment]
i tried, it couldn't find you

**Comment by Paradoxum** [comment]
Weird, I'm in the unraid one at least https://discord.com/invite/qWPbc8R

**Comment by Paradoxum** [comment]
I accidentally cleared my whole plex cache drive, so I started the whole thing from scratch. I added the movies library but turned off any kind of generation until evertything had been scanned and mapped fully and the server was idle, then I optimized the db, searched it again, and shut it down after enabling thumbnails for the library. turned it back on. idle, as it should be outside of task time now. I run the script, I get the same error as before on the whole library.

I was able to generate a lot of movies with it at some point early on. I will leave thumb gen off until I get this fixed because I had 240gb of metadata I wanna get back nice and fast with the gpu.

**Comment by Paradoxum** [comment]
[Req#8ba] (Capabilities) Platform 'Linux' not matched by plugin platform requirements

lots of this in the plex console when I run the generator, could that be anything?

**Comment by stevezau** [comment]
@Paradoxum did you resolve it?

**Comment by stevezau** [comment]
Issue is closed. The user wasn't mapping their paths correctly.
