### ISSUE TITLE
Throwing a lot of errors for Audiobooks and Music

### ISSUE THREAD

**Issue by ChristianMalazarte** [stevezau/plex_generate_vid_previews#37]
Any way to exclude certain libraries? Thanks!

I have them set to exclude from home screen and global search, is that the reason why?

**Comment by stevezau** [comment]
@ChristianMalazarte can you expand on what you mean when you say "I have them set to exclude from home screen and global search, is that the reason why?"

**Comment by ChristianMalazarte** [comment]
Thanks, I just added some code to filter out some libraries. But yeah the thing I was talking about is an option in Plex when you edit the library.

`    plex = PlexServer(PLEX_URL, PLEX_TOKEN, session=sess)

    for section in plex.library.sections():
        if section.title == 'Audiobooks' or section.title == 'Music' or section.title == 'Lectures':
            continue`

**Comment by stevezau** [comment]
makes sense.. just not sure on the best way to implement it yet.

**Comment by stevezau** [comment]
https://github.com/stevezau/plex_generate_vid_previews/commit/cd53bd96110888611aee5a0fb9934c142b47c05c should fix it

**Comment by ChristianMalazarte** [comment]
Awesome thanks!
