### ISSUE TITLE
Generation Issue [Unraid]

### ISSUE THREAD

**Issue by Paradoxum** [stevezau/plex_generate_vid_previews#38]
Thought this should have a better title.

https://www.reddit.com/r/linux/comments/xs8zff/to_my_fellow_linux_nvidia_users_use/

Could this help at all?

I emailed you my DBs and other info @stevezau

**Comment by stevezau** [comment]
@Paradoxum is this the same issue as the one you closed?

**Comment by Paradoxum** [comment]
> @Paradoxum is this the same issue as the one you closed?

https://github.com/stevezau/plex_generate_vid_previews/issues/36#issuecomment-2170041945

Yes it wouldn't let me change the title and it no longer really had anything to do with what it was.

https://forums.plex.tv/t/possible-new-bug-in-file-name-detection/880234

Could this be related?

**Comment by Paradoxum** [comment]
I'm going to  take my 6950XT out of my gaming rig that is being rebuilt and stick it in the server and try with that. It's watercooled though so I need to create a small loop for it so I don't fry it. Although looking now it seems you maybe can't even use amd cards for plex.

https://support.plex.tv/articles/201242707-plex-media-scanner-via-command-line/
some options here like 
![image](https://github.com/stevezau/plex_generate_vid_previews/assets/6451395/5135ebdc-fc13-4d90-8f30-02c3580f2421)

possible options to specify overwiring old ones etc?

**Comment by stevezau** [comment]
@Paradoxum you are jumping around a bit and it is not clear what the issue is anymore.. I am trying to understand what the actual problem is with you running this script?

I thought the issue was the error messages you posted in the other issue? i.e this one 
![image](https://github.com/stevezau/plex_generate_vid_previews/assets/6075483/eccd66d8-5d8d-4bd9-ae39-10c89b9d6e7b)


Is that still the problem?

**Comment by stevezau** [comment]
@Paradoxum let me know.. and in the meantime please try again with the latest version as I've made a few changes which might help t-shoot.

**Comment by Paradoxum** [comment]
Yes, it is the same issue, but I have nothing to go from except the 
vague error so I am trying anything.


------ Original Message ------
From "Steve Adams" ***@***.***>
To "stevezau/plex_generate_vid_previews" 
***@***.***>
Cc "Paradoxum" ***@***.***>; "Mention" 
***@***.***>
Date 17/06/2024 04:33:46 AM
Subject Re: [stevezau/plex_generate_vid_previews] Generation Issue 
[Unraid] (Issue #38)

**Comment by stevezau** [comment]
Try again with the latest tag or version 1.1 and show me the output

**Comment by Paradoxum** [comment]
![image](https://github.com/stevezau/plex_generate_vid_previews/assets/6451395/11cde471-c23b-4968-bc9b-bd73b80be25b)

**Comment by Paradoxum** [comment]
![image](https://github.com/stevezau/plex_generate_vid_previews/assets/6451395/69860daf-d44d-4a66-94d3-a4c437ca855d)

![image](https://github.com/stevezau/plex_generate_vid_previews/assets/6451395/31933ffa-a72a-4845-ba63-6466eadf61ef)

![image](https://github.com/stevezau/plex_generate_vid_previews/assets/6451395/16e5e6be-decf-4a5f-8e00-54537a79cb95)

![image](https://github.com/stevezau/plex_generate_vid_previews/assets/6451395/6eed1067-13e2-4714-b09c-185837d88fad)

**Comment by Paradoxum** [comment]
This is my compose file:

version: '3'
services:
  previews:
    image: stevezzau/plex_generate_vid_previews:latest
    environment:
      - PLEX_URL=http://192.168.2.90:32400
      - PLEX_TOKEN=
      - PLEX_BIF_FRAME_INTERVAL=1
      - THUMBNAIL_QUALITY=2
      - PLEX_LOCAL_MEDIA_PATH=/mnt/thumbs
      - TMP_FOLDER=/tmp/thumbs
      - PLEX_TIMEOUT=30
      - GPU_THREADS=4
      - CPU_THREADS=4
    volumes:
      - /mnt/user/Plex/Plex Media Server/Media/localhost/:/mnt/thumbs/
      - /mnt/user/data/media/anime/movies/:/mnt/user/data/media/anime/movies/
      - /mnt/user/data/media/tv shows/:/mnt/user/data/media/tv shows/
      - /mnt/user/data/media/movies/:/mnt/user/data/media/movies/
      - /mnt/user/data/media/anime/series/:/mnt/user/data/media/anime/series/
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia

are the volume mounts case sensitive?

**Comment by Paradoxum** [comment]
I changed all my plex paths to match exactly the external paths, eg /mnt/user/data/media/anime/series/:/mnt/user/data/media/anime/series/ on both plex and the script.

I tried playing around with those other variables and with this:

version: '3'
services:
  previews:
    image: stevezzau/plex_generate_vid_previews:latest
    environment:
      - PLEX_URL=http://192.168.2.90:32400
      - PLEX_TOKEN=zMQQsXyEu98GHAsEasNx
      - PLEX_BIF_FRAME_INTERVAL=1
      - THUMBNAIL_QUALITY=2
      - PLEX_LOCAL_VIDEOS_PATH_MAPPING=/tmp/thumbs
      - PLEX_VIDEOS_PATH_MAPPING=/mnt/user/data/media/
      - PLEX_LOCAL_MEDIA_PATH=/mnt/user/data/media/
      - TMP_FOLDER=/tmp/thumbs
      - PLEX_TIMEOUT=30
      - GPU_THREADS=4
      - CPU_THREADS=4
    volumes:
      - /mnt/user/Plex/Plex Media Server/Media/localhost/:/tmp/thumbs
      - /mnt/user/data/media/anime/movies/:/mnt/user/data/media/anime/movies/
      - /mnt/user/data/media/tv/:/mnt/user/data/media/tv/
      - /mnt/user/data/media/movies/:/mnt/user/data/media/movies/
      - /mnt/user/data/media/anime/series/:/mnt/user/data/media/anime/series/
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia

I got this error:
![image](https://github.com/stevezau/plex_generate_vid_previews/assets/6451395/694117ff-7e12-467a-a565-b4fd94a1137e)

**Comment by Paradoxum** [comment]
Did you get the database files I uploaded etc? How about discord?

**Comment by stevezau** [comment]
i msgd you on discord @Paradoxum

**Comment by stevezau** [comment]
Issue is closed. The user wasn't mapping their paths correctly.
