### ISSUE TITLE
Thumbnails not working

### ISSUE THREAD

**Issue by derpderpington** [stevezau/plex_generate_vid_previews#41]
I am not getting any errors and I believe it is making the thumbnails but in Plex I am not seeing them. Not sure what to troubleshoot next.
"
2024/07/20 14:45:33 | ℹ️  - Getting the media files from library 'Movies'
2024/07/20 14:45:37 | ℹ️  - Got 1538 media files for library Movies
2024/07/20 14:46:13 | ℹ️  - Generated Video Preview for /data/media/movies/All 
The Money In The World (2017)/All the Money in the World (2017) Bluray-1080p.mp4
HW=True TIME=35.9seconds SPEED=225x
"
But then in Plex under "All the Money in the World" no thumbnail previews.

Here's my docker with plex token obfuscated.
docker run
  -d
  --name='plex_generate_vid_previews'
  --net='toadnet'
  -e TZ="America/Anchorage"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="Hypnotoad"
  -e HOST_CONTAINERNAME="plex_generate_vid_previews"
  -e 'PLEX_LOCAL_MEDIA_PATH'='/config'
  -e 'PLEX_URL'='http://192.168.0.246:32400'
  -e 'PLEX_BIF_FRAME_INTERVAL'='10'
  -e 'PLEX_TOKEN'='XXXXXXXXXX'
  -e 'NVIDIA_DRIVER_CAPABILITIES'='all'
  -e 'NVIDIA_VISIBLE_DEVICES'='GPU-a035efad-d0dd-7a56-7b4e-0812e31e3ce0'
  -e 'PLEX_LOCAL_MEDIA_PATH'='/data/media'
  -l net.unraid.docker.managed=dockerman
  -v '/mnt/user/plexMedia/':'/config':'rw'
  -v '/mnt/user/data/media/':'/data/media':'rw'
  --runtime=nvidia 'stevezzau/plex_generate_vid_previews'
d90ac8a145955fdd1d7642ba1875b9497497b198f81a990017f17394c30eb493

**Comment by derpderpington** [comment]
-v '/mnt/user/plexMedia/':'/config':'rw' needed to be corrected to -v '/mnt/user/plexMedia/Media':'/config':'rw' however that did not seem to fix it either.

**Comment by stevezau** [comment]
Hi @derpderpington, 

You have conflicting env variables. In the above, I can see 
```
-e 'PLEX_LOCAL_MEDIA_PATH'='/config'
-e 'PLEX_LOCAL_MEDIA_PATH'='/data/media'
```

PLEX_LOCAL_MEDIA_PATH needs to be set to where the Media folder is on your system. By default, it is usually below the plex (Library/Application Support/Plex Media Server/Media). In that folder you should see a folder called localhost.

Can you confirm you have set that variable correctly and it is mapped correctly?

**Comment by derpderpington** [comment]
Dang thought I set that to PLEX_VIDEOS_PATH_MAPPING but turns out I didn't even need it. Thanks. Now that's it's running I've noticed my gpu usage go down after about 5 hours of it running. It used to do a full video at x300 speed but now I see as low as x5.5 and taking 900 seconds. HW = True. No other processes on my GPU and I have a GTC 1070. Any ideas?

**Comment by stevezau** [comment]
@derpderpington does it still look like it is using the GPU or CPU? I think it depends on what video type/format/codec used which will determine how fast it will go...

**Comment by derpderpington** [comment]
I set the cpu threads to 0 but some files are just slower than others. I'm sure it's still faster than plex. However new issue. Setting the PLEX_LOCAL_MEDIA_PATH to the /media was not working. I spoke too soon yesterday saying it was working because I checked and none of the thumbnails worked and in the /media next to the localhost folder was a bunch of the single character alphanumeric folders. Once I changed it to /media/localhost it is now working verified. I appreciate the assistance.

**Comment by stevezau** [comment]
@derpderpington you are right. I just pushed a fix to correct this. It will now check for the localhost folder under PLEX_LOCAL_MEDIA_PATH and if it does not exist it will error out.

So, I will push a new version.. you'll need to edit PLEX_LOCAL_MEDIA_PATH to point to media not media/localhost

**Comment by derpderpington** [comment]
@espentruls hey that was actually wrong on my config part. But here is the exact setup. In my plex_generate_vid_previews I have Container Variable: PLEX_LOCAL_MEDIA_PATH set to "/config". Then I have Container Path: /config mapped to "/mnt/user/plexMedia/Media/". Next is Container Path: /data/media mapped to "/mnt/user/data/media/". I also have a fee more variables set such as the
PLEX_URL'='http://192.168.0.246:32400'  'PLEX_BIF_FRAME_INTERVAL'='10'  'PLEX_TOKEN'='XXXXXXXXXX'  'NVIDIA_DRIVER_CAPABILITIES'='all'  'NVIDIA_VISIBLE_DEVICES'='GPU a035efad-d0dd-7a56-7b4e 0812e31e3ce0
Also most notably you need to go to hit "Basic View" in the top right so you can see advanced settings and add --runtime=nvidia to the "Extra Parameters".

My plex container is mapped such that /config = /mnt/user/plexMedia/ amd /data/media = /mnt/user/data/media/

Please let me know if you have any questions as it was fun setting this up and hopefully I can get other people up on Unraid as well!
