### ISSUE TITLE
Terminating thread with return code -28 (No space left on device)

### ISSUE THREAD

**Issue by espentruls** [stevezau/plex_generate_vid_previews#42]
Terminating thread with return code -28 (No space
left on device)

I get this error message when it tries to do 4k dovi/hdr full Blu-ray remuxes or the encoded equivalent. This script works flawlessly with tv shows but errors out when the file size and/or format gets too big or complicated.

**Comment by stevezau** [comment]
@espentruls, can you paste the output?

The error suggests you ran out of space.... Is that the issue?  or are you suggesting something else is wrong?

**Comment by espentruls** [comment]
I have 44.9TB left of free storage. So there is something else happening here. It tells me that error and then does fine on 10-15 shows. and then errors again on the same run. so it has nothing to do with storage space. maybe its something to do with how plex manages it. when i put it the interval to 2 it error on every episode, now at 5 it only error on larger files and complex files with dovi/hdr

**Comment by stevezau** [comment]
@espentruls ok great, so all resolved?

**Comment by espentruls** [comment]
@stevezau I'm running it now. I'm gonna go delete a few thumbnails that I know failed last time and then report back to you by tomorrow. Just in case

**Comment by espentruls** [comment]
Suddenly I got another problem. It's been working for hours and when it got to House of the Dragon i got this error

```
2024/07/24 13:27:55 | ❌  - ['  Hardware device setup failed for decoder: 
Generic error in an external library', ' Error initializing a simple 
filtergraph', 'Error opening output file 
/dev/shm/plex_generate_previews/1fd0bdc7643fb609c41f05eb31bbf4f6378cda70/img-%06
d.jpg.', 'Error opening output files: Generic error in an external library', '']
```
Looks like its got something to do with my 1050ti. But shouldn't this just let the cpu do it instead of failing it?

**Comment by espentruls** [comment]
Im noticing now that it happens to every new tv show that is in dolby vision with hdr 10 fallback.

**Comment by stevezau** [comment]
Hi, @espentruls, how are you mounting the folders in your container? Specifically how are you setting the TMP_FOLDER variable? And, what memory was assigned to the container? 

It uses /dev/shm/plex_generate_previews by default.. Which is using ram.. I wonder if that's running out of space due to the size of DV+HDR

**Comment by stevezau** [comment]
How did you go @espentruls ?

**Comment by espentruls** [comment]
@stevezau Sorry for the late reply. I haven't set an option for TMP_Folder so that explains it. Im probably running out of ram. I only have 60GB. I will try to map it to my NVME drive and see if that fixes the problem

**Comment by stevezau** [comment]
No worries. LMK how you go.

**Comment by espentruls** [comment]
I still get errors after remapping @stevezau 

```
2024/07/26 11:18:26 | ❌  - ['  Hardware device setup failed for decoder: 
Generic error in an external library', ' Error initializing a simple 
filtergraph', 'Error opening output file 
/data/pgvp/8432c84d675cf0b48db54ecf91a88b6faf12d0b7/img-%06d.jpg.', 'Error 
opening output files: Generic error in an external library', '']
2024/07/26 11:18:26 | ❌  - Problem trying to ffmpeg images for 
/data/media/tv/Severance (2022) {imdb-tt11280740}/Season 01/Severance (2022) - 
S01E01 - Good News About Hell [ATVP WEBDL-2160p][DV HDR10Plus][EAC3 Atmos 
5.1][HEVC]-HONE.mkv
2024/07/26 11:18:26 | ℹ️  - Generated Video Preview for /data/media/tv/Severance
(2022) {imdb-tt11280740}/Season 01/Severance (2022) - S01E01 - Good News About 
Hell [ATVP WEBDL-2160p][DV HDR10Plus][EAC3 Atmos 5.1][HEVC]-HONE.mkv HW=True 
TIME=1.2seconds SPEED=[]x 
```

**Comment by espentruls** [comment]
This is my full setup.

```
docker run
  -d
  --name='plex_generate_vid_previews'
  --net='vision'
  -e TZ="Europe/Berlin"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="VISION"
  -e HOST_CONTAINERNAME="plex_generate_vid_previews"
  -e 'PLEX_URL'='http://192.168.1.147:32400'
  -e 'PLEX_TOKEN'='<REDACTED>'
  -e 'PLEX_BIF_FRAME_INTERVAL'='5'
  -e 'PLEX_LOCAL_MEDIA_PATH'='/media'
  -e 'THUMBNAIL_QUALITY'='4'
  -e 'GPU_THREADS'='4'
  -e 'CPU_THREADS'='4'
  -e 'NVIDIA_VISIBLE_DEVICES'='GPU-628807a8-0de4-30a3-89e5-e57a1c83bd06'
  -e 'NVIDIA_DRIVER_CAPABILITIES'='all'
  -e 'TMP_FOLDER'='/data/pgvp'
  -l net.unraid.docker.managed=dockerman
  -v '/mnt/user/data':'/data':'rw'
  -v '/mnt/system_cache/appdata/plex/Library/Application Support/Plex Media Server/Media':'/media':'rw'
  --runtime=nvidia 'stevezzau/plex_generate_vid_previews'
```

**Comment by espentruls** [comment]
I'm trying to reduce GPU threads and increase CPU threads to what i have set-up in tdarr. Maybe that'll fix it

  -e 'GPU_THREADS'='3'
  -e 'CPU_THREADS'='6'

**Comment by espentruls** [comment]
@stevezau I can see all threads in nvtop even the cpu ones. It looks to be running fine now when i reduced the amount of threads. It looks to still be using a lot of ram, so it has nothing to do with the tmp location. That uses only a few MB.

**Comment by stevezau** [comment]
Hey @espentruls ah ok. so perhaps the card was running out of memory? 

Anyway, looks like it is resolved now? I can close this?

**Comment by stevezau** [comment]
@espentruls i will close this now, if this is in error please let me know.

**Comment by mikebernat** [comment]
I know this is closed but I ran into the same error message and wanted to share my fix. I found increasing the amount of GPU_THREADS at some point I would start seeing this error even though I had plenty of disk space and video memory:

```
[' Terminating thread with return code -28 (No space left on device)', ' video:2295KiB audio:0KiB subtitle:0KiB other streams:0KiB global headers:0KiB muxing overhead: unknown',
'frame=  245 fps=4.5 q=4.0 Lsize=N/A time=00:40:50.00 bitrate=N/A speed=44.8x    ', 'Conversion failed!', '']
```

Troubleshooting within the container showed /dev/shm was running out of space. Increasing the shm-size fixed the issue for me by adding --shm-size=1gb to the run command:


```
docker run -it --rm \
  --name=plex_generate_vid_previews \
  --runtime=nvidia \
  --shm-size=8gb \
  -e NVIDIA_VISIBLE_DEVICES=all \
  -e PUID=1000 \
  -e PGID=1000 \
  -e PLEX_URL='http://localhost:32400' \
  -e PLEX_TOKEN='XXXXXX' \
  -e PLEX_BIF_FRAME_INTERVAL=2 \
  -e THUMBNAIL_QUALITY=4 \
  -e PLEX_LOCAL_MEDIA_PATH='/config/plex/Library/Application Support/Plex Media Server/Media' \
  -e GPU_THREADS=5 \
  -e CPU_THREADS=5 \
  -v /your/media/files:/your/media/files \
  -v /plex/folder:/plex/folder \
  stevezzau/plex_generate_vid_previews:latest
```

Hope this helps someone else!
