### ISSUE TITLE
Working perfectly fine for days but after an update...

### ISSUE THREAD

**Issue by Paradoxum** [stevezau/plex_generate_vid_previews#43]
![image](https://github.com/user-attachments/assets/460aa88c-aec3-4cda-aace-d6fd9c64fbe2)

It was generating everything fine for days then I stopped it to run a parity sync on my array, after updating it when it runs I now get this - I did not change anything in the compose file.

![image](https://github.com/user-attachments/assets/bfcfefeb-4506-4ac9-91ea-0cae1542f7b8)

What did you change? can you revert whatever it was? /tmp/ should be RAM, so it should create the folders itself there? I'm not sure why it has stopped working. 

![image](https://github.com/user-attachments/assets/2d7a2cb1-9234-403e-92f1-a9d374917e78)
I was generating thumbs for everything at high quality every second (just because I have the space so I can), and I was up to 500GB metadata, but like I say now it has stopped working.

thank you

**Comment by stevezau** [comment]
@Paradoxum that was a bug that i fixed.

All you need to do is change

```
/mnt/user/Plex/Plex Media Server/Media/localhost:/tmp/thumbs/
```
to

```
/mnt/user/Plex/Plex Media Server/Media:/tmp/thumbs/
```

**Comment by Paradoxum** [comment]
thanks I'll give it a try.

**Comment by Paradoxum** [comment]
Oh also..

![image](https://github.com/user-attachments/assets/76428053-e2e3-4aa2-906b-8da49ec34d13)


If I wanted to have it use the Plex icon, what would I put in here?

Thanks

**Comment by stevezau** [comment]
@Paradoxum I am not sure, that's a question for whatever tool you are using..
