### ISSUE TITLE
NVMLError_LibraryNotFound: NVML Shared  Library Not Found

### ISSUE THREAD

**Issue by Skyline404** [stevezau/plex_generate_vid_previews#47]
Latest docker image

```
2024/09/12 19:03:02 | ❌  - Error generating images for /storage/series/American
Horror Story (2011) /Season 05/American Horror Story (2011) - S05E05 - Room 
Service [WEBDL-1080p][AC3 2.0].mkv. `NVMLError_LibraryNotFound: NVML Shared 
Library Not Found` error when generating images
2024/09/12 19:03:03 | ❌  - Error generating images for /storage/series/American
Horror Story (2011) /Season 05/American Horror Story (2011) - S05E06 - Room 33 
[WEBDL-1080p][AC3 2.0].mkv. `NVMLError_LibraryNotFound: NVML Shared Library Not 
Found` error when generating images
2024/09/12 19:03:03 | ❌  - Error generating images for /storage/series/American
Horror Story (2011) /Season 05/American Horror Story (2011) - S05E08 - The Ten 
Commandments Killer [WEBDL-1080p][AC3 2.0].mkv. `NVMLError_LibraryNotFound: NVML
Shared Library Not Found` error when generating images
```

**Comment by stevezau** [comment]
@Skyline404 do you have a NVIDIA GPU? 

Did you install the nvidia-container-toolkit as per https://github.com/stevezau/plex_generate_vid_previews?tab=readme-ov-file#install-nvidia-container-toolkit

And, set runtime: nvidia ?

**Comment by stevezau** [comment]
Ah, it wasn't designed for that, as I think Plex should use all the CPUs when generating images by default. Are you not seeing that? I could modify it to support CPU only?

**Comment by stevezau** [comment]
@Skyline404 please try the latest version (1.2). It should detect GPU and if not found default to CPU which i think will meet your requirement.

**Comment by stevezau** [comment]
@Skyline404 just following up on this one. thanks

**Comment by vantilborghk** [comment]
hi i'm having some issues getting my gpu detected, i'm running fedora 40, nvidia-container-toolkit is installed and i can see my gpu but when i start your container i get the NVML shared library not found. i tried setting no-cgroups to false already as i found in another thread but that didn't help either. 

sudo docker run --rm --runtime=nvidia --gpus all ubuntu nvidia-smi
Wed Oct  9 14:49:33 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.58.02              Driver Version: 555.58.02      CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1070 Ti     Off |   00000000:08:00.0  On |                  N/A |
|  0%   47C    P8             13W /  180W |     531MiB /   8192MiB |      1%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
+-----------------------------------------------------------------------------------------+



anything else i can try?

**Comment by stevezau** [comment]
@vantilborghk hmm, can you share the logs/output of when you try start the container?

I need to see the logs before it tries to process files.

**Comment by vantilborghk** [comment]
sure, it doesn't say much besides the error that is on this topic, why i commented on it here 

+] Running 2/2
 ✔ Network plex-preview_default       Created                                                                                                0.3s 
 ✔ Container plex-preview-previews-1  Created                                                                                                0.1s 
Attaching to previews-1
previews-1  | 2024/10/10 11:11:19 | ℹ️  - GPU Detection (with AMD Support) was recently added 
previews-1  | to this script.
previews-1  | 2024/10/10 11:11:19 | ℹ️  - Please log issues here 
previews-1  | https://github.com/stevezau/plex_generate_vid_previews/issues
previews-1  | 2024/10/10 11:11:19 | ⚠️  - Error initializing NVIDIA GPU detection NVML Shared 
previews-1  | Library Not Found. NVIDIA GPUs will not be detected.
previews-1  | 2024/10/10 11:11:19 | ⚠️  - Error initializing AMD GPU detection: 'ROCM_PATH'. 
previews-1  | AMD GPUs will not be detected.
previews-1  | 2024/10/10 11:11:19 | ⚠️  - No GPUs detected. Defaulting to CPU ONLY.
previews-1  | 2024/10/10 11:11:19 | ⚠️  - If you think this is an error please log an issue 
previews-1  | here https://github.com/stevezau/plex_generate_vid_previews/issues
previews-1  | 2024/10/10 11:11:20 | ℹ️  - Getting the media files from library 'Movies'

after that it starts processing on cpu of course

br

**Comment by stevezau** [comment]
hmm odd, can you share your docker run command @vantilborghk

**Comment by stevezau** [comment]
@vantilborghk any update ?

**Comment by stevezau** [comment]
@vantilborghk i just made some updated, can you try again.

**Comment by stevezau** [comment]
Great, closing this one. 

@vantilborghk if you still have issues please open a new issue.
