### ISSUE TITLE
Remote path mapping

### ISSUE THREAD

**Issue by dkadavarath** [stevezau/plex_generate_vid_previews#49]
Not sure if this is possible at all, but I'm trying to run this script on a more powerful PC with Nvidia GPU to create thumbnails for Plex running on a separate weaker machine. This script will have to access Plex media folder and the Media itself through the network.

PLEX_URL=https://192.168.0.191:32400/
PLEX_TOKEN=xxxxxxx
PLEX_BIF_FRAME_INTERVAL=10
THUMBNAIL_QUALITY=4
PLEX_LOCAL_MEDIA_PATH=\\\192.168.0.191\Media
TMP_FOLDER=C:\tmp
PLEX_TIMEOUT=60
PLEX_LOCAL_VIDEOS_PATH_MAPPING=\\\192.168.0.191\Data (Path script sees to the Media)
PLEX_VIDEOS_PATH_MAPPING=C:\Data (Path Plex sees to the media)
GPU_THREADS=4
CPU_THREADS=4

All the media is present under the C:\Data folder on the weaker machine, and shared over network to the script. I'm getting the "Skipping as file not found" error while running the script. From the looks of it, the script is trying to access the file locally instead of over the network. Please help.

**Comment by stevezau** [comment]
Hi @dkadavarath, you need to set PLEX_LOCAL_VIDEOS_PATH_MAPPING and PLEX_VIDEOS_PATH_MAPPING correctly. 

Can you confirm three things and ill help you set them:

1. Where are your plex config files located on the "more powerful PC"
2. Where are your media files on the local plex server located? What's the path?
3. Where is the path you have mapped locally on the "more powerful PC"

**Comment by dkadavarath** [comment]
Where are your plex config files located on the "more powerful PC"
           They're not on the "more powerful PC", they're on the "weaker" one. I've shared that directory over SMB as below.
           "\\192.168.0.191\Media"
Where are your media files on the local plex server located? What's the path?
           For the "weaker system" with the Plex server on it, it'd be "C:\Data"
Where is the path you have mapped locally on the "more powerful PC"
            For the "more powerful PC" with the script on it, it'd be "\\192.168.0.191\Data"

**Comment by stevezau** [comment]
Hi @dkadavarath, the script does not support accessing files via a SMB share. It also uses ffmpeg to generate the images which also does not support access via smb share. 

So, you'll need to mount them.. You need 
- Access to the plex "Media" folder in the plex config path. 
- Access to the media files.

I haven't used windows for a long time but i think you can do something like

```
net use Z: \\server\share
```

**Comment by dkadavarath** [comment]
> Hi @dkadavarath, the script does not support accessing files via a SMB share. It also uses ffmpeg to generate the images which also does not support access via smb share.
> 
> So, you'll need to mount them.. You need
> 
> * Access to the plex "Media" folder in the plex config path.
> * Access to the media files.
> 
> I haven't used windows for a long time but i think you can do something like
> 
> ```
> net use Z: \\server\share
> ```

I solved it by replacing the direct paths in the Plex server with smb shares. It works now, without mounting. 

![image](https://github.com/user-attachments/assets/6e8f3b18-83bf-4eda-ba3f-9dab7338864c)

**Comment by stevezau** [comment]
I'm surprised that work.. lol. Ok I'll close this one out

**Comment by Crunch41** [comment]
@dkadavarath 

Sorry to reopen this issue, Hope it's alright. Would you be able to explain how you updated the paths & env file to get the script to work over smb? Can't figure out if it's a script change or something to do on the plex server. Would then be a good addition to the readme for anyone with the same problem in the future. Seems like no matter what I update the .env with on windows the script only appears to look at the plex server's media path vs the manually input ones so I've been stumped trying to figure this out haha.

**Comment by stevezau** [comment]
@Crunch41 can you share your config settings and the errors?

**Comment by dkadavarath** [comment]
> @dkadavarath
> 
> Sorry to comment on the closed issue, Hope it's alright. Would you be able to explain how you updated the paths & env file to get the script to work over smb? Can't figure out if it's a script change or something to do on the plex server. Would then be a good addition to the readme for anyone with the same problem in the future. Seems like no matter what I update the .env with on windows the script only appears to look at the plex server's media path vs the manually input ones so I've been stumped trying to figure this out haha.

No worries. I'll explain with some examples.

Path Plex server sees to the media: C:\Media
Path Plex server sees to the database: C:\Users\User\AppData\Local\Database
Path the script sees to the Media: \\192.168.0.191\Media
Path the script sees to the database: \\192.168.0.191\Database

This is probably what you're working with. Let me know if there's any changes.
What I did was, to change the situation as below.

Path Plex server sees to the media: **\\192.168.0.191\Media**
Path Plex server sees to the database: C:\Users\User\AppData\Local\Database
Path the script sees to the Media: \\192.168.0.191\Media
Path the script sees to the database: \\192.168.0.191\Database

Plex can directly access SMB fine, even if it's localhost. I went through each library and

- Added the new SMB location to each of them. 
- Disabled the empty trash after each scan.
- Did a full scan (Probably not required)
- Removed the direct paths from the libraries.
- Did another full scan.

Now the media path will be same for both Plex and script.
It's time consuming but simple fix.

**Comment by Crunch41** [comment]
> > @dkadavarath
> > Sorry to comment on the closed issue, Hope it's alright. Would you be able to explain how you updated the paths & env file to get the script to work over smb? Can't figure out if it's a script change or something to do on the plex server. Would then be a good addition to the readme for anyone with the same problem in the future. Seems like no matter what I update the .env with on windows the script only appears to look at the plex server's media path vs the manually input ones so I've been stumped trying to figure this out haha.
> 
> No worries. I'll explain with some examples.
> 
> Path Plex server sees to the media: C:\Media Path Plex server sees to the database: C:\Users\User\AppData\Local\Database Path the script sees to the Media: \192.168.0.191\Media Path the script sees to the database: \192.168.0.191\Database
> 
> This is probably what you're working with. Let me know if there's any changes. What I did was, to change the situation as below.
> 
> Path Plex server sees to the media: **\192.168.0.191\Media** Path Plex server sees to the database: C:\Users\User\AppData\Local\Database Path the script sees to the Media: \192.168.0.191\Media Path the script sees to the database: \192.168.0.191\Database
> 
> Plex can directly access SMB fine, even if it's localhost. I went through each library and
> 
>     * Added the new SMB location to each of them.
> 
>     * Disabled the empty trash after each scan.
> 
>     * Did a full scan (Probably not required)
> 
>     * Removed the direct paths from the libraries.
> 
>     * Did another full scan.
> 
> 
> Now the media path will be same for both Plex and script. It's time consuming but simple fix.


Was mid reply when you posted haha, I'm running the script on windows and my plex server is running on unraid so I can't pass through my media to plex via the smb path windows has so I think I'm out of luck with this one unfortunately.

**Comment by dkadavarath** [comment]
Have you just tried typing in the network path in the WebUI? Even on Windows, Plex doesn't indicate in any way that it supports SMB without mounting. I just typed in the full network path and it just started working. Maybe try for a small library?

**Comment by Crunch41** [comment]
I can modify the plex library to match the smb path that windows sees but as the files "don't exist" on the plex side it looks like the script still searches the original "valid" library path which in my case it searches through /media/plex/movies vs windows seeing it along the lines of \\SERVER\media\plex\movies if I navigate to it normally.

**Comment by dkadavarath** [comment]
Seems like you missed the last two steps. You've to remove the direct path permanently and do a full rescan again.

**Comment by Crunch41** [comment]
Appreciate the help with this one, I've been working at it for a while & have figured it out on my end so I hope to repay the favor by leaving this guide which is in the attached txt file which should hopefully cover a baseline for unraid users using a windows pc for generation as a guide if you want to use it. @stevezau 

[githubunraid.txt](https://github.com/user-attachments/files/17290558/githubunraid.txt)

Unrelated I'm now having an issue while generating my progress is showing HW=False and is maxing out my cpu usage even with cpu threads set to 0 and my gpu usage is next to nothing. Any ideas as to why my gpu wouldn't be the main device in use? The script does detect my GPU as nvidia so not sure if that's how it's intended to run?

**Comment by stevezau** [comment]
@Crunch41 ill take a look at the instructions a bit later when i have time.. 

RE the GPU issue. I made a recent update which i was unable to test due to lack of access to GPUs. Can you create a new issue and paste the log output?

**Comment by Crunch41** [comment]
Will do!

**Comment by dkadavarath** [comment]
> Unrelated I'm now having an issue while generating my progress is showing HW=False and is maxing out my cpu usage even with cpu threads set to 0 and my gpu usage is next to nothing. Any ideas as to why my gpu wouldn't be the main device in use? The script does detect my GPU as nvidia so not sure if that's how it's intended to run?

I think you're missing one of the toolkits or driver components. I've been exclusively using my GPU for non-gaming stuff like this and hence have installed multiple things, so can't specifically say which one it is. Let @stevezau look at the logs for a better idea.

**Comment by stevezau** [comment]
@Crunch41 are you still having issues with the path mappings?

**Comment by Crunch41** [comment]
@stevezau Nope got that sorted, Everything I did to get the script to function & pickup the path mapping is in the txt file I added in my above post

**Comment by Crunch41** [comment]
@stevezau Looks to be good to me, I imagine anyone following along that uses unraid would be able to modify paths as required to suit how they personally have their paths setup but I suppose if you wanted to be sure just mention up top that you'd need to change the name from server to whatever you've personally set your server's host name as that would usually be the smb share name in the windows network tab.
