### ISSUE TITLE
Unraid Setup

### ISSUE THREAD

**Issue by confuzedplayer** [stevezau/plex_generate_vid_previews#54]
Guide for Unraid
Note: In this example, the server is named server for the network share on Windows, and the SMB share has user-accessible permissions to your media folder. This guide follows the [TRaSH Guide](https://trash-guides.info/) for folder naming structures & was done using the linuxserver plex docker image.

Steps
Add a Second Container Path:

In your Plex Docker container settings, add a second container path for /server/media/plex/.
Map the host path as you normally would (e.g., /mnt/user/media/plex/).
Update Plex Library Path Mappings:

Open Plex and delete all of your current library path mappings.
Replace them with paths following this format (you must add a second / yourself, as Plex will only show the mount with one):
//server/media/plex/<name-of-media-folder>.
Example: //server/media/plex/tv
Modify the Script's Environment File:

The script’s .env file only needs one specific adjustment for Unraid:
Set PLEX_LOCAL_MEDIA_PATH as follows:
PLEX_LOCAL_MEDIA_PATH=\\SERVER\appdata\plex\Library\Application Support\Plex Media Server\Media
Grant Script Permissions to the Media Folder:

In order for the script to write to the Media folder in the Plex appdata directory, you may need to adjust the permissions.
I used the following command in the Unraid console:
chmod -R 777 /mnt/cache/appdata/plex/Library/Application\ Support/Plex\ Media\ Server/Media/
Run the Script:

After running the script, your GPU should begin working.
Note: The script may appear to be frozen on 0 files, but you can still see thumbnails being created in the temporary folder you specified, and it should eventually start to update in your terminal.

Is this for having it run on unraid to a remote path ? 

Im trying to figure out how i can use this on my unraid server using the default mounted path. 

I apologize in advance as my knowledge in all this is very minimal.

**Comment by dezerving** [comment]
> Is this for having it run on unraid to a remote path ?

Yes, in that guide they're using SMB. If you're new to this, that guide could get complicated.

> Im trying to figure out how i can use this on my unraid server using the default mounted path.

I can try and help. We should clarify a few things though.

---
### 1. Where are you running the script?

### 2. Where is your Plex server?
What is the path to the Plex Media folder?		
> This is your plex database folder, **NOT** your tv/movie file folder(s)

	- (eg: /path_to/plex/Library/Application Support/Plex Media Server/Media)
		
### 3. Where is your media located (movies/tv shows files)?
What is the path to your tv/movie folder file(s)
> Only needed if the machine where your script is and your Plex server have **different paths to the media**

Answering this could help you get started.

**Comment by confuzedplayer** [comment]
Thank you for your help i really do appreciate it. 

1. Where are you running the script?

The original plan was to run it in a docker on my unraid server or just locally using unraid user scripts. Which ever method is easier. 

2. Where is your Plex server? 

- /mnt/cache/appdata/plex/Library/Application Support/Plex Media Server/Media)

3. Where is your media located (movies/tv shows files)? ( I follow trash guide mainly)

- /mnt/user/data/media

Only needed if the machine where your script is and your Plex server have different paths to the media 
- I believe it will be the same path

**Comment by dezerving** [comment]
Okay so great, I'd recommend Docker based on everything you told me. 

> [!TIP]
> If you aren't yet I'd recommend using the compose plugin on Unraid App Store. 
> See: https://forums.unraid.net/topic/114415-plugin-docker-compose-manager/
 
Now you'll want to setup your environment variables. See the [environment variables](https://github.com/stevezau/plex_generate_vid_previews#environment-variables) section for more details/customizations. I'll focus on the paths/volumes. You can also just add these variables/volumes to an `.env` file or directly in the Unraid Web GUI.

For custom paths and volumes you really just need the PLEX_LOCAL_MEDIA_PATH variable and two volumes (the path to your Plex db media folder and path to your actual media).

Lastly, make sure your docker container has access to the volumes (in the same way that Plex sees them). I forgot to ask you but how does Plex see your media? I'll go with the assumption that Plex sees it under `/data/media` so you might have movies at `/data/media/movies` in Plex. So you'll want to map the docker volumes the same way you did for Plex on Unraid.

What your `compose.yaml` file should look like:

```yaml
services:
  previews:
    image: stevezzau/plex_generate_vid_previews:latest
    environment:
      - PLEX_URL=https://xxxxxx.plex.direct:32400 
      - PLEX_TOKEN=your-plex-token 
      - PLEX_BIF_FRAME_INTERVAL=10
      - THUMBNAIL_QUALITY=4
      - PLEX_LOCAL_MEDIA_PATH=/mnt/plexdb
    volumes:
      - /mnt/cache/appdata/plex/Library/Application Support/Plex Media Server/Media:/mnt/plexdb
      - /mnt/user/data/media:/data/media
```

> [!NOTE]
> If you're not comfortable with the compose plugin and would rather use the Unraid Docker template method then just make sure to map out the environment variables and volumes correctly within the Unraid GUI the same way as I showed above.

 
> Also do you disable generate thumbnail preview in plex?

I personally do, yeah but you don't have to and I think most people just use this as a bulk tool and then have Plex start taking care of new media thumbnails again.

**Comment by confuzedplayer** [comment]
wow perfect. thank you for this, ill give this a try and see how it goes. I'm ok with the docker compose plugin but i think ill try to see if i can figure out how to use the unraid GUI first if not ill go docker compose route. 

In regards to the cpu threads, does the plex default generate thumbnail only use a few threads went creating the thumbnails? I have not installed my nvidia gpu yet to the server , was going to test out the cpu threads to see how fast it can go. I mainly use intel arc on my unraid server so was curious if the cpu would be good enough, if not ill add the gpu.

**Comment by confuzedplayer** [comment]
I believe i got it working for CPU. 

2024/11/08 23:31:00 | ℹ️  - GPU Detection (with AMD Support) was recently added 
to this script.
2024/11/08 23:31:00 | ℹ️  - Please log issues here 
https://github.com/stevezau/plex_generate_vid_previews/issues
2024/11/08 23:31:00 | ⚠️  - Error initializing NVIDIA GPU detection NVML Shared 
Library Not Found. NVIDIA GPUs will not be detected.
2024/11/08 23:31:00 | ⚠️  - Error initializing AMD GPU detection: 'ROCM_PATH'. 
AMD GPUs will not be detected.
2024/11/08 23:31:00 | ⚠️  - No GPUs detected. Defaulting to CPU ONLY.
2024/11/08 23:31:00 | ⚠️  - If you think this is an error please log an issue 
here https://github.com/stevezau/plex_generate_vid_previews/issues
2024/11/08 23:31:00 | ℹ️  - Getting the media files from library '4KMovies'
2024/11/08 23:31:00 | ℹ️  - Got 26 media files for library 4KMovies

I don't see any progress information but i can see my cpu working at 100%. 

1) Does it show progress progress information only for GPU? or do i have to let it run for some time before it start showing "working" progress information? I'll probably add a gpu soon. 

2) Also when it creates the thumbnails, how do i go about deleting them in the future? could i delete it using the plex delete preview thumbnails? 

Thank you again for your help

**Comment by dezerving** [comment]
That's great. Glad you got it working.

1. Yes just keep it running it will start to show progress as it completes each file. For some reason progress output is not as robust on Docker yet. I know there is something in the works for better logging so we'll see when that's implemented.

2. Yes just delete with Plex.

3. I don't know if it picks up exactly where it left off like in progress files but it will continue from the last completed file.

**Comment by confuzedplayer** [comment]
Thank you again @dezerving . I was able to install my nvidia gpu and I believe i got it running. Says the following

2024/11/09 16:15:37 | ℹ️  - GPU Detection (with AMD Support) was recently added 
to this script.
2024/11/09 16:15:37 | ℹ️  - Please log issues here 
https://github.com/stevezau/plex_generate_vid_previews/issues
2024/11/09 16:15:38 | ℹ️  - Found NVIDIA GPU
2024/11/09 16:15:38 | ℹ️  - Getting the media files from library '4KMovies'
2024/11/09 16:15:38 | ℹ️  - Got 26 media files for library 4KMovies


Will see if it shows any update as i just started it. 

How many threads could i use, using quadro p400?

**Comment by confuzedplayer** [comment]
2024/11/09 17:11:03 | 🐞  - Trying to determine how many GPU threads running
2024/11/09 17:11:03 | 🐞  - Counted 0 ffmpeg GPU threads running
2024/11/09 17:11:03 | 🐞  - Running ffmpeg
2024/11/09 17:11:03 | 🐞  - /usr/local/bin/ffmpeg -loglevel info -skip_frame:v 
nokey -hwaccel cuda -threads:0 1 -i

had log level debug on and it says threads:0 is that normal?

**Comment by confuzedplayer** [comment]
I got the gpu working but some reason i felt like my gpu was going very slow, slower than cpu. Could have been I'm using an ancient card. Would be nice to have intel arc working with this but until then.

Thank you again @dezerving . Ill mark this as resolved.

**Comment by stevezau** [comment]
@confuzedplayer do you believe it is not using the GPU correctly? If not let me know and we can t-shoot.

**Comment by confuzedplayer** [comment]
@stevezau I'm not sure what was the issue. I can see that it was using my gpu but felt really slow. It might have been an issue with my gpu i'm not sure. i ended up removing the nvidia gpu from my server. I mainly use the intel arc card . Ill wait for the WIP PR next week. Thank you though
