### ISSUE TITLE
Title: Clarification on Plex Default Thumbnail Quality and Automation for Libraries

### ISSUE THREAD

**Issue by AlexFigas** [stevezau/plex_generate_vid_previews#56]
Could you clarify the default quality Plex uses for generating thumbnails? I’m looking to optimize thumbnail generation for speed while maintaining the same quality as the Plex default. Additionally, is it possible to automate this process so that it applies to every newly added library?

**Comment by stevezau** [comment]
Hey @AlexFigas, I can’t recall what Plex defaults to for image quality. You can check by looking at your system processes when Plex is running thumbnail generation. Look for the Plex processes, and you should see all the ffmpeg settings being used. My library is up to date, so I can’t check it on my end, but if you share the command, I can tell you what it’s using.

Regarding the quality setting, it’s tied to the -q:v option in FFmpeg. This controls the quality of the extracted frames, affecting the compression level and overall image quality. 

When you mention automation, is there a specific reason you’d want a script for this instead of letting Plex handle new additions? The script was primarily designed for regenerating thumbnails for an entire library as a one-time operation.

**Comment by stevezau** [comment]
Actually, it just ran for me. output s
```
Plex Transcoder -codec:v h264 -skip_frame:v nokey -i /myfile.mkv -threads 0 -nostats -q 3 -loglevel quiet -filter_complex [0:V:0] fps=fps=0.500000:round=up,scale=w=320:h=240:force_original_aspect_ratio=decrease [out] -map [out] /my/bundle/path/28ecd12f3c64d4b3c8669d6720e3d2a76b04434.bundle/Contents/Indexes/tmp/img-%06d.jpg -progressurl http://127.0.0.1:32400/video/:/transcode/session/bif/2443a911-ca8f-4e43-b3f9-b64fe4a821f5/progress```

So the default quality is set to 3.  ("-q 3)

**Comment by AlexFigas** [comment]
Thanks!

I've been managing this directly through Plex, but I think it would be helpful to mention the default quality settings for Plex in the README. If you're open to contributions, I'd be happy to update the README to include that.

As for the automation, no worries—it's not necessary. I initially thought the script could track its progress and handle what it had or hadn’t done automatically.

**Comment by AlexFigas** [comment]
Something like this:

|            Variables             | Function                                                                                                                                    |
|:--------------------------------:|---------------------------------------------------------------------------------------------------------------------------------------------|
|            `PLEX_URL`            | Plex server URL. (eg: http://localhost:32400)                                                                                               |
|           `PLEX_TOKEN`           | Plex Token. ([click here for how to get a token](https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/)) |
|    `PLEX_BIF_FRAME_INTERVAL`     | Interval between preview images (default: 5, plex default: 2)                                                                                                |
|     `PLEX_LOCAL_MEDIA_PATH`      | Path to Plex Media folder (eg: /path_to/plex/Library/Application Support/Plex Media Server/Media)                                           |
|       `THUMBNAIL_QUALITY`        | Preview image quality (2-6, default: 4, plex default: 3). 2 being highest quality and largest file size and 6 being lowest quality and smallest file size.   |
|           `TMP_FOLDER`           | Temp folder for image generation. (default: /dev/shm/plex_generate_previews)                                                                |
|          `PLEX_TIMEOUT`          | Timeout for Plex API requests in seconds (default: 60). If you have a large library, you might need to increase the timeout.                |
|          `GPU_THREADS`           | Number of GPU threads for preview generation (default: 4)                                                                                   |
|          `CPU_THREADS`           | Number of CPU threads for preview generation (default: 4)                                                                                   |
| `PLEX_LOCAL_VIDEOS_PATH_MAPPING` | Leave blank unless you need to map your local media files to a remote path (eg: '/path/this/script/sees/to/video/library')                  |
|    `PLEX_VIDEOS_PATH_MAPPING`    | Leave blank unless you need to map your local media files to a remote path (eg: '/path/plex/sees/to/video/library')                         |
|           `LOG_LEVEL`            | Set to debug for troubleshooting                                                                                                            |

**Comment by stevezau** [comment]
Thanks @AlexFigas i updated the readme. 

Good to close this issue now?

**Comment by AlexFigas** [comment]
Thx! Closed :)
