### ISSUE TITLE
Multi-Part Episodes Processed Multiple Times Simultaneously Causing Errors

### ISSUE THREAD

**Issue by jasonsansone** [stevezau/plex_generate_vid_previews#6]
Any episode where the file is a multi-part (ie S01E01-E02) is processed as many times as it appears in Plex.  This is logical since Plex treats it as Part 1 and Part 2 with reference to the same file and so it would pull from the database sequentially.  The problem is that the same bundle identifier is used.  When using multi-threading, the processing occurs simultaneously with multiple instances of ffmpeg overwriting each other.  The script then tries to pull the files from the same folder into a .bif.  Whichever instance occurs later in time throws errors for missing jpg frame files.  This wouldn't occur if the .bif existed prior to analysis since the code looks for an existing .bif.  It only occurs because the Plex db tells the script to process the file twice and the second (or third, etc) ffmpeg instance begins prior to the final creation of the .bif by the first instance.

I see two solutions.  One obvious work-around is to limit the script to only one CPU or GPU thread.  That worked for debugging and narrowing down the cause of the errors.  The better solution is to change the setup and teardown of temp bundle folders to allow detection of an existing process and skip multiple processing for the same bundle.  I will attempt a commit after testing.

**Comment by stevezau** [comment]
@jasonsansone i'm not sure on this one and won't have time to look into it anytime in the near future. I'm open to PR's if you figure it out :)

**Comment by jasonsansone** [comment]
I made a commit which resolves this.  I believe the commit should be part of the still pending PR, but as previously mentioned, I am a total git newbie.

**Comment by stevezau** [comment]
I just merged it. I Also committed some minor tweaks to your PR https://github.com/stevezau/plex_generate_vid_previews/commit/7f155abb3c6a7bfa63df196da6b8fcc5db9df234.

**Comment by jasonsansone** [comment]
Awesome, thank you!

**Comment by BuSHari** [comment]
There is still an issue with Multi-Part episodes

**Comment by GR3ee3N** [comment]
> There is still an issue with Multi-Part episodes
> 
> ```
> concurrent.futures.process._RemoteTraceback: 
> """
> Traceback (most recent call last):
>   File "/usr/lib/python3.12/concurrent/futures/process.py", line 263, in _process_worker
>     r = call_item.fn(*call_item.args, **call_item.kwargs)
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/app/plex_generate_previews.py", line 350, in process_item
>     shutil.rmtree(tmp_path)
>   File "/usr/lib/python3.12/shutil.py", line 796, in rmtree
>     onexc(os.rmdir, path, err)
>   File "/usr/lib/python3.12/shutil.py", line 794, in rmtree
>     os.rmdir(path, dir_fd=dir_fd)
> OSError: [Errno 39] Directory not empty: '/tmp/plex_generate_previews/4762eb7bcbb2b5909c09e2cac2247c33a8d1bfae'
> """
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/app/plex_generate_previews.py", line 417, in <module>
>     run(gpu)
>   File "/app/plex_generate_previews.py", line 377, in run
>     future.result()
>   File "/usr/lib/python3.12/concurrent/futures/_base.py", line 456, in result
>     return self.__get_result()
>            ^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
>     raise self._exception
> OSError: [Errno 39] Directory not empty: '/tmp/plex_generate_previews/4762eb7bcbb2b5909c09e2cac2247c33a8d1bfae'
> Riddlin and Life On The Inside [WEBDL-1080p][EAC3 5.1]-HBN.mkv at 
> /plex_media/localhost/1/fffb170f647902d3f0a31af3d203b614e787c3b.bundle/Contents/
> Indexes/index-sd.bif
> 2025/01/04 19:07:56 | 🐞  - Generating bundle_file for /videos/Kids/Kids TV/Kiff
> (2023) {tvdb-405112}/Season 01/Kiff (2023) - S01E32-E33 - Everyday Im Riddlin 
> Riddlin and Life On The Inside [WEBDL-1080p][EAC3 5.1]-HBN.mkv at 
> /plex_media/localhost/1/fffb170f647902d3f0a31af3d203b614e787c3b.bundle/Contents/
> Indexes/index-sd.bif
> 2025/01/04 19:07:56 | 🐞  - Trying to determine how many GPU threads running
> 2025/01/04 19:07:56 | 🐞  - Counted 0 ffmpeg GPU threads running
> 2025/01/04 19:07:56 | 🐞  - Running ffmpeg
> 2025/01/04 19:07:56 | 🐞  - /usr/local/bin/ffmpeg -loglevel info -skip_frame:v 
> nokey -hwaccel cuda -threads:0 1 -i /videos/Kids/Kids TV/Kiff (2023) 
> {tvdb-405112}/Season 01/Kiff (2023) - S01E32-E33 - Everyday Im Riddlin Riddlin 
> and Life On The Inside [WEBDL-1080p][EAC3 5.1]-HBN.mkv -an -sn -dn -q:v 3 -vf 
> fps=fps=0.2:round=up,scale=w=320:h=240:force_original_aspect_ratio=decrease 
> /tmp/plex_generate_previews/1fffb170f647902d3f0a31af3d203b614e787c3b/img-%06d.jp
> g
> 2025/01/04 19:07:56 | 🐞  - Trying to determine how many GPU threads running
> 2025/01/04 19:07:56 | 🐞  - Counted 0 ffmpeg GPU threads running
> 2025/01/04 19:07:56 | 🐞  - Running ffmpeg
> 2025/01/04 19:07:56 | 🐞  - /usr/local/bin/ffmpeg -loglevel info -skip_frame:v 
> nokey -hwaccel cuda -threads:0 1 -i /videos/Kids/Kids TV/Kiff (2023) 
> {tvdb-405112}/Season 01/Kiff (2023) - S01E32-E33 - Everyday Im Riddlin Riddlin 
> and Life On The Inside [WEBDL-1080p][EAC3 5.1]-HBN.mkv -an -sn -dn -q:v 3 -vf 
> fps=fps=0.2:round=up,scale=w=320:h=240:force_original_aspect_ratio=decrease 
> /tmp/plex_generate_previews/1fffb170f647902d3f0a31af3d203b614e787c3b/img-%06d.jp
> g
> 2025/01/04 19:08:04 | 🐞  - FFMPEG Command output
> 2025/01/04 19:08:04 | 🐞  - b''
> 2025/01/04 19:08:04 | 🐞  - FFMPEG Command output
> 2025/01/04 19:08:04 | 🐞  - b''
> 2025/01/04 19:08:04 | ❌  - Error generating images for /videos/Kids/Kids 
> TV/Kiff (2023) {tvdb-405112}/Season 01/Kiff (2023) - S01E03-E04 - Pool Party and
> Road Trip [WEBDL-1080p][EAC3 5.1]-HBN.mkv. `FileNotFoundError: [Errno 2] No such
> file or directory: 
> '/tmp/plex_generate_previews/100b4efa08c8b2c059d2fbeac06d322eff7ae3a4/img-000028
> .jpg' -> 
> '/tmp/plex_generate_previews/100b4efa08c8b2c059d2fbeac06d322eff7ae3a4/0000000135
> .jpg'` error when generating images
> 2025/01/04 19:08:04 | ℹ️  - Generated Video Preview for /videos/Kids/Kids TV/Kiff
> (2023) {tvdb-405112}/Season 01/Kiff (2023) - S01E03-E04 - Pool Party and Road 
> Trip [WEBDL-1080p][EAC3 5.1]-HBN.mkv HW=True TIME=13.8seconds SPEED=104x 
> 2025/01/04 19:08:05 | 🐞  - FFMPEG Command output
> 2025/01/04 19:08:05 | 🐞  - b''
> 2025/01/04 19:08:05 | ℹ️  - Generated Video Preview for /videos/Kids/Kids TV/Kiff
> (2023) {tvdb-405112}/Season 01/Kiff (2023) - S01E32-E33 - Everyday Im Riddlin 
> Riddlin and Life On The Inside [WEBDL-1080p][EAC3 5.1]-HBN.mkv HW=True 
> TIME=8.8seconds SPEED=164x 
> 2025/01/04 19:08:05 | 🐞  - FFMPEG Command output
> 2025/01/04 19:08:05 | 🐞  - b''
> 2025/01/04 19:08:05 | ℹ️  - Generated Video Preview for /videos/Kids/Kids TV/Kiff
> (2023) {tvdb-405112}/Season 01/Kiff (2023) - S01E32-E33 - Everyday Im Riddlin 
> Riddlin and Life On The Inside [WEBDL-1080p][EAC3 5.1]-HBN.mkv HW=True 
> TIME=8.8seconds SPEED=165x 
> 2025/01/04 19:08:05 | ❌  - Error generating images for /videos/Kids/Kids 
> TV/Kiff (2023) {tvdb-405112}/Season 01/Kiff (2023) - S01E32-E33 - Everyday Im 
> Riddlin Riddlin and Life On The Inside [WEBDL-1080p][EAC3 5.1]-HBN.mkv. 
> `FileNotFoundError:[Errno 2] No such file or directory: 
> '/tmp/plex_generate_previews/1fffb170f647902d3f0a31af3d203b614e787c3b'` error 
> when generating bif
> ⠦ Working... ━━━━━━━━━━━━━━━╸                          40% 0:00:11 1156/2921
> ```

Same errors for me on multi episode files.

**Comment by stevezau** [comment]
Yes, i'm really not sure how to handle multi-part files. not sure how plex does it.

**Comment by GR3ee3N** [comment]
I think I'll investigate this later. Right now, things seem to get so messed up at some point that the process hard crashes, and I'm stuck halfway through my library.

**Comment by stevezau** [comment]
Should be fixed in latest version.
