### ISSUE TITLE
PLEX_URL only required if Plex isn't running locally

### ISSUE THREAD

**Issue by jasonsansone** [stevezau/plex_generate_vid_previews#7]
The Plex Direct URL works great, but 127.0.0.1 also works if the plex install is running on the same instance as the script.  Using localhost loopback is faster, avoids unnecessary DNS traffic, and more reliable.

**Comment by stevezau** [comment]
What's stopping someone from putting 127.0.01 in the PLEX_URL var? It should still work, right?

**Comment by jasonsansone** [comment]
"What's stopping someone from putting 127.0.01 in the PLEX_URL var? It should still work, right?"
Nothing stops them, in fact it works fine.  To clarify, my only suggestion is to update the docs to state that 127.0.0.1 works fine as an alternative to the plex.direct URL.  No need to change code.  Or the issue now exists as reference for anyone that comes along... if that is ever more than us.

"Also, if using xxxx.plex.direct it should resolve to the server IP. In addition, your DNS should cache locally so I can't see how it can significantly speed up given most of the time spend is in compute not network?"

If running your own DNS (pihole, pfsense, etc) and cycling through a large database with existing preview thumbnails, it quickly floods the DNS server with thousands of requests.  I had this problem in testing where it was hammering my internal DNS server.  Loopback solved that.

**Comment by stevezau** [comment]
update docs.
