### ISSUE TITLE
Ability to use Intel QSV / VAAPI to generate thumbnails

### ISSUE THREAD

**Issue by Ge082** [stevezau/plex_generate_vid_previews#8]
Hi.

I see that your script works by offloading some stuffs on the GPU, whick I have to guess is Nvidia only at the time being.
I do wonder if the script would, one day, be compatible with VAAPI / QSV for Intel based iGPUs ?

**Comment by Ge082** [comment]
I am able to use VAAPI for 1080p stuffs and working great, however 4k HDR throws me errors, which I still have to figure out

**Comment by stevezau** [comment]
Closing as won't fix. Open to PR's
